import test from 'node:test';import assert from 'node:assert/strict';
import {makeAnalytics,probabilityStats,timings,compactEvidence,updateAudit,agreementCounts,downsample,trimRetained,DETAIL_LIMIT,POINT_LIMIT,schemas,numeric} from '../lib/turn-analytics';
import {legalMoves,slide,newGame,move} from '../public/engine';
import {MatchController} from '../lib/match-controller';
import {reliableDecision} from '../lib/reliability';
import {buildBlind,validateBlind} from '../lib/blind-policies';
const board=[2,2,4,0,8,4,0,0,2,0,0,0,0,0,0,0];
function fixture(){const g=newGame('analytics-fixture');g.board=board.slice();const built=buildBlind(board,'blind-board',undefined,n=>n-1),label='B',direction=built.mapping[label];move(g,direction);return {move:g.moves,policy:'blind-board',before:board.slice(),after:g.board,direction,gain:slide(board,direction).score,spawn:{index:g.board.findIndex((v,i)=>v!==slide(board,direction).board[i]),value:2},ms:100,model:'fixture',probabilities:Object.fromEntries(legalMoves(board).map(d=>[d,d===direction?1:0])),usage:null,evidence:{version:'blind-ablation-1',exact_request:built.request,candidate_mapping_not_sent:built.mapping,selected_candidate:label,candidate_probabilities:Object.fromEntries(Object.keys(built.mapping).map(k=>[k,k===label?1:0])),audit_not_sent:{status:'pending',agrees_expectimax:null,agrees_ntuple:false}}};}

test('timing fields stay in their stages; audit and configured delay do not enter total',()=>{const t=timings('blind-dual',900,{totalMs:900,uiDelay:500,browserParseMs:3,serverMs:850,timing:{queue_wait_ms:5,worker_queue_ms:2,candidate_generation_formatting_ms:4,board_features_ms:100,expectimax_evidence_ms:200,ntuple_total_ms:20,ntuple_internal_ms:18,ntuple_compute_ms:.01,jev_http_wait_ms:400}});assert.equal(t.queue.ms,7);assert.equal(t.features.ms,100);assert.equal(t.expectimax.ms,200);assert.equal(t.nativeQueue.ms,2);assert.equal(t.nativeTransport.ms,17.99);assert.equal(t.nativeQueue.kind,'upper-bound');assert.equal(t.browserTransport.ms,47);assert.equal(t.total.ms,900);assert.equal(t.uiDelay.ms,500);assert.equal(t.audit.ms,null);assert.equal(t.parsing.ms,3);});
test('unknown timings remain unavailable; Ultra end-to-end cannot be allocated per move',()=>{const t=timings('blind-board',100);assert.equal(t.jevHttp.ms,null);assert.equal(t.parsing.ms,null);assert.equal(t.nativeCompute.kind,'not-applicable');assert.equal(timings('search',2,{ultra:true}).total.ms,null);assert.equal(timings('human',0).total.ms,null);});
test('entropy uses normalized probability mass and margin uses the top two outputs',()=>{assert.deepEqual(probabilityStats({A:.5,B:.5},'A'),{selectedProbability:.5,margin:0,entropyBits:1,probabilityMass:1});const p=probabilityStats({A:.66,B:.33},'B');assert.equal(p.selectedProbability,.33);assert.equal(p.margin,.33);assert.ok(Math.abs(p.entropyBits!-.918295834)<1e-8);assert.equal(probabilityStats({A:0,B:0},'A').entropyBits,null);assert.equal(probabilityStats(null,null).margin,null);});
test('candidate mapping, common fields, seeded spawn offset and choices remain correct',()=>{const r=fixture(),a=makeAnalytics(r,'analytics-fixture',r.gain,{attempts:1});assert.equal(a.selectedCandidate,'B');assert.equal(a.candidates.find(c=>c.label==='B')!.direction,r.direction);assert.deepEqual(a.candidates.find(c=>c.label==='B')!.board,slide(board,r.direction).board);assert.equal(a.spawn.sequence,3);assert.equal(a.spawn.randomDrawOffset,4);assert.deepEqual(a.legal,legalMoves(board));assert.equal(a.scoreIncrease,r.gain);assert.equal(a.score,r.gain);assert.equal(a.highest,Math.max(...r.after));const selected=validateBlind({answers:{candidate:{type:'choice',choice:'B',probabilities:r.evidence.candidate_probabilities}}},r.evidence.candidate_mapping_not_sent,board);assert.equal(selected.direction,r.direction);assert.deepEqual(r.before,board);});
test('missing Jev usage remains unavailable and evidence availability is not invented',()=>{const a=makeAnalytics(fixture(),'seed',4);assert.equal(a.inputTokens,null);assert.equal(a.outputTokens,null);assert.ok(a.candidates.every(c=>c.searchValue===null&&c.learnedValue===null));assert.equal(a.agreesSearch,null);assert.equal(a.overridesSearch,null);assert.equal(a.overridesLearned,true);});
test('ranks use supplied values only and preserve ties',()=>{const r=fixture();for(const c of Object.values(r.evidence.exact_request.state.candidates) as any[])c.search={normalized_expected_value:.5,player_depth:3};const a=makeAnalytics(r,'seed',4);assert.ok(a.candidates.every(c=>c.searchRank===1&&c.learnedRank===null));});
test('agreement counters keep unknowns separate and never call overrides improvements',()=>{const counts=agreementCounts([{agreesSearch:true,agreesLearned:true},{agreesSearch:false,agreesLearned:false},{agreesSearch:true,agreesLearned:null},{agreesSearch:null,agreesLearned:true}]);assert.deepEqual(counts,{searchKnown:3,searchAgreed:2,learnedKnown:3,learnedAgreed:2,bothKnown:2,both:1,neither:1,searchOverrides:1,learnedOverrides:1});});
test('audit updates are asynchronous, do not change moves, and ignore restarted boards',async()=>{let resolve!:(r:any)=>void;const gate=new Promise<any>(r=>resolve=r);const m=new MatchController(()=>{},{search:()=>gate,jev:async(p:any)=>({...fixture(),direction:legalMoves(p.board)[0],evidence:{audit_not_sent:{status:'pending'}}})});m.configure('compare',['blind-board','search']);const b=m.boards[0];await m.tick(b);assert.equal(b.game.moves,1);const r=b.records[0],oldTime=r.analytics!.timing.total.ms;resolve({direction:r.direction});await Promise.resolve();assert.equal(r.analytics!.agreesSearch,true);assert.equal(r.analytics!.timing.total.ms,oldTime);assert.ok(r.analytics!.timing.audit.ms!==null);m.dispose();});
test('downsampling keeps game ends, disagreements, low-margin, large-reward and error events',()=>{const a=makeAnalytics(fixture(),'seed',4);const rows=Array.from({length:10000},(_,i)=>({move:i+1,event:false}));for(const i of [33,111,345,888,9998])rows[i].event=true;const small=downsample(rows,100);for(const i of [33,111,345,888,9998])assert.ok(small.includes(rows[i]));assert.equal(small[0].move,1);assert.equal(small.at(-1)!.move,10000);assert.ok(small.length<120);assert.equal(a.event,true);});
test('100000 synthetic history entries stay inside the documented in-memory limits',()=>{const records=Array.from({length:100000},(_,i)=>({move:100000-i})),points=Array.from({length:100000},(_,i)=>({move:i+1}));trimRetained(records,points);assert.equal(records.length,DETAIL_LIMIT);assert.equal(points.length,POINT_LIMIT);assert.equal(records[0].move,100000);assert.equal(points.at(-1)!.move,100000);});
test('sanitization removes secrets, auth headers, internal paths and raw payloads; prompt schemas are shared',()=>{const r=fixture();const evidence={...r.evidence,authorization:'Bearer SECRET',raw_response:{secret:'SECRET'},state:{headers:{Authorization:'SECRET'},api_key:'SECRET',file_path:'C:\\Users\\secret',internal:'C:\\Users\\secret',ok:1}};const a=compactEvidence(evidence),b=compactEvidence(evidence),json=JSON.stringify(a);assert.doesNotMatch(json,/SECRET|C:\\\\Users|Authorization|api_key/);assert.equal(a.exact_request.questions,b.exact_request.questions);assert.ok(schemas.size<=64);assert.equal(a.state.ok,1);assert.equal(compactEvidence({state:{blob:'x'.repeat(100000)}}).state.blob.length,8192);});
test('numeric rows retain move index and events without storing boards or prompt strings',()=>{const a=makeAnalytics(fixture(),'seed',4),n=numeric(a);assert.equal(n.move,1);assert.equal(n.score,4);assert.ok(!('before' in n));assert.ok(!('candidates' in n));assert.equal(n.event,a.event);});
test('retry telemetry counts attempts and missing usage without altering retry behavior',async()=>{let calls=0;const legal=legalMoves(board);const result=await reliableDecision({board},{canStart:()=>true,onStatus:()=>{},onAttempt:()=>{},sleep:async()=>{},fetcher:async()=>{calls++;return new Response(JSON.stringify(calls===1?{error:'Temporary',code:'rate_limit',retryable:true,attempted:true}:{direction:legal[0],probabilities:Object.fromEntries(legal.map((d,i)=>[d,i?0:1])),usage:{input_tokens:10,output_tokens:2},ms:4}),{status:calls===1?429:200})}});assert.equal(calls,2);assert.equal(result.direction,legal[0]);assert.equal(result.telemetry?.attempts,2);assert.equal(result.telemetry?.retries,1);assert.equal(result.telemetry?.inputTokens,null);assert.equal(result.telemetry?.errorCategory,'rate_limit');});
import {presentTerms} from '../lib/evidence-glossary';
import {measureJev,timedJevFetch} from '../lib/jev-observation';
test('field guide describes only evidence actually present in a move',()=>{const basic=presentTerms({current_board:board,candidates:{A:{resulting_board:[board.slice(0,4)],immediate_merge_reward:0}}});assert.deepEqual(basic.map(t=>t.name),['Current board','Resulting board','Immediate merge reward']);assert.ok(presentTerms({normalized_afterstate_value:.5}).some(t=>t.name==='Normalized learned value'));assert.ok(!basic.some(t=>t.name.includes('search')));});
test('HTTP observation preserves request and response and stores durations only',async()=>{const original=globalThis.fetch;let captured:any;globalThis.fetch=async(input,init)=>{captured={input,init};return new Response('fixture-response',{status:200});};try{const init={method:'POST',headers:{Authorization:'Bearer fixture-secret'},body:'unchanged-fixture-body'};const {result,span}=await measureJev(()=>timedJevFetch('https://example.invalid',init));assert.equal(captured.init,init);assert.equal(await result.text(),'fixture-response');assert.ok(span.jev_http_wait_ms!>=0);assert.doesNotMatch(JSON.stringify(span),/fixture|Bearer|Authorization/);}finally{globalThis.fetch=original;}});

import {usageOf as deploymentUsage} from '../lib/provider-usage';
import {usageOf as legacyUsage} from '../jev-baseline.js';
test('deployment usage parsing matches frozen baseline without importing its credential loader',()=>{for(const result of [undefined,null,{}, {usage:{input_tokens:1,output_tokens:2}}, {usage:{input_tokens:0,output_tokens:0}}, {usage:{input_tokens:1}}, {usage:{input_tokens:-1,output_tokens:2}}, {usage:{input_tokens:1.5,output_tokens:2}}])assert.deepEqual(deploymentUsage(result),legacyUsage(result));});
