import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';import {legalMoves,heuristic,slide} from '../public/engine.js';import {policyEvidence} from '../decision-policies.js';
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1440,height:900},hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const tick=ms=>new Promise(r=>setTimeout(r,ms)),counts=new Map(),active=new Map();let max=0,rawFailures=0,rawIllegal=false,gate=null;const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};const moves=id=>page.getByTestId(id+'-moves').textContent().then(Number);const idle=()=>page.waitForFunction(()=>![...document.querySelectorAll('.status-pill')].some(e=>/waiting for Jev|retrying|^running$/.test(e.textContent)));
const readBoard=label=>page.getByRole('group',{name:label,exact:true}).locator('[data-value]').evaluateAll(els=>{const b=Array(16).fill(0);for(const e of els){const m=e.getAttribute('aria-label').match(/Row (\d), column (\d)/);b[(Number(m[1])-1)*4+Number(m[2])-1]=Number(e.dataset.value);}return b;});
try{
 await page.route('**/api/decision',async route=>{const p=route.request().postDataJSON();counts.set(p.policy,(counts.get(p.policy)||0)+1);active.set(p.match,(active.get(p.match)||0)+1);max=Math.max(max,active.get(p.match));if(p.policy==='raw'&&gate)await gate.promise;let body,status=200;if(p.policy==='raw'&&rawFailures>0){rawFailures--;status=429;body={error:'Temporary test rate limit.',retryable:true,code:'rate_limit',attempted:false};}else{const legal=legalMoves(p.board),direction=heuristic(p.board);body={direction:p.policy==='raw'&&rawIllegal?'diagonal':direction,probabilities:Object.fromEntries(legal.map(d=>[d,d===direction?1:0])),model:'mock-only',ms:10,usage:{input_tokens:10,output_tokens:2},attempted:true,evidence:policyEvidence(p.board,{score:p.score,moveNumber:p.moves},p.policy,p.correction)};rawIllegal=false;}active.set(p.match,active.get(p.match)-1);await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});});
 await page.goto('http://127.0.0.1:2048');await page.getByText('Jev ready',{exact:true}).waitFor();await page.evaluate(()=>document.fonts.ready);assert.ok(await page.evaluate(()=>[...document.fonts].some(f=>f.status==='loaded'&&f.family.includes('dmSans'))));assert.equal(await page.getByRole('combobox',{name:'Opponent',exact:true}).locator('option').count(),6);
 await page.getByRole('combobox',{name:'Opponent',exact:true}).selectOption('raw');await page.getByRole('combobox',{name:'Speed',exact:true}).selectOption('fast');await page.locator('.lab-intro h1').click();await page.keyboard.press('ArrowLeft');assert.equal(await moves('human'),1);await page.getByRole('textbox',{name:'Seed',exact:true}).focus();await page.keyboard.press('ArrowRight');assert.equal(await moves('human'),1);await page.locator('#restart').click();const start=await readBoard('You board');await page.locator('#step').click();await idle();assert.equal(await moves('raw'),1);
 await page.getByRole('button',{name:'Inspect Raw Jev',exact:true}).click();await page.getByRole('dialog').waitFor();assert.equal(await page.getByRole('img',{name:'Decision input board: '+start.join(', '),exact:true}).count(),1);assert.ok(await page.locator('.inspector-prob meter').count()>0);await page.locator('dialog summary').click();assert.match(await page.locator('dialog pre').textContent(),/legal_directions/);await page.getByRole('button',{name:'Close inspector'}).click();
 // Pause and restart in flight.
 gate=deferred();await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('[data-policy=raw] .status-pill').textContent==='waiting for Jev');await page.locator('#run').click();const n=counts.get('raw');gate.resolve();gate=null;await idle();await tick(150);assert.equal(counts.get('raw'),n);
 gate=deferred();await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('[data-policy=raw] .status-pill').textContent==='waiting for Jev');await page.locator('#restart').click();const held=counts.get('raw');await page.locator('#run').click();await tick(100);assert.equal(counts.get('raw'),held);await page.locator('#run').click();gate.resolve();gate=null;await tick(200);assert.equal(await moves('raw'),0);assert.deepEqual(await readBoard('You board'),start);
 rawIllegal=true;await page.locator('#step').click();await idle();assert.equal(await moves('raw'),1);
 await page.getByRole('tab',{name:'Compare',exact:true}).click();await page.locator('.policy-picker label').filter({hasText:'Strategy Jev'}).locator('input').check();assert.equal(await page.locator('.game-board').count(),5);await page.locator('#step').click();await idle();for(const id of ['raw','strategy','feature','assisted','search'])assert.equal(await moves(id),1);assert.equal(await page.locator('.recharts-line').count(),5);
 for(const measure of ['highest','empty','ms','score']){await page.getByRole('combobox',{name:'Chart measure'}).selectOption(measure);assert.ok(await page.locator('.recharts-line-curve').count()>0);}
 await page.getByRole('button',{name:'Inspect Expectimax-assisted Jev',exact:true}).click();await page.getByRole('dialog').waitFor();assert.ok(await page.locator('.inspector-facts tbody tr').count()>0);await page.locator('dialog summary').click();assert.match(await page.locator('dialog pre').textContent(),/expected_quality/);await page.getByRole('button',{name:'Close inspector'}).click();
 // Hide retains its board and policy, show restores it.
 const hide=page.getByRole('region',{name:'Board visibility'});const visibility=page.locator('.lab-visibility button').filter({hasText:'Raw Jev'});await visibility.click();assert.equal(await page.locator('.game-board').count(),4);await visibility.click();assert.equal(await moves('raw'),1);
 await page.locator('.policy-picker label').filter({hasText:'Strategy Jev'}).locator('input').uncheck();await page.locator('.policy-picker label').filter({hasText:'Feature Jev'}).locator('input').uncheck();await page.locator('.policy-picker label').filter({hasText:'Expectimax-assisted Jev'}).locator('input').uncheck();assert.equal(await page.locator('.game-board').count(),2);
 rawFailures=99;await page.locator('#run').click();await page.locator('[data-policy=raw] .lab-error').waitFor({timeout:15000});assert.equal(await moves('raw'),0);assert.ok(await moves('search')>0);rawFailures=0;await page.getByRole('button',{name:'Retry Raw Jev'}).click();await page.waitForFunction(()=>Number(document.querySelector('[data-testid=raw-moves]').textContent)>=2);await page.locator('#run').click();await idle();assert.equal(await page.locator('[data-policy=raw] .lab-error').count(),0);
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByRole('tab',{name:'Play',exact:true}).click();await page.getByRole('button',{name:'Move left',exact:true}).tap();assert.equal(await moves('human'),1);const board=page.getByRole('group',{name:'You board',exact:true});await board.scrollIntoViewIfNeeded();const box=await board.boundingBox(),cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+30,y:box.y+box.height/2,id:0}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+170,y:box.y+box.height/2,id:0}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await moves('human'),2);
 await page.getByRole('tab',{name:'How it works'}).click();await page.locator('.lab-about h1').click();await page.keyboard.press('ArrowDown');await page.getByRole('tab',{name:'Play',exact:true}).click();assert.equal(await moves('human'),2);
 assert.equal(max,1);assert.deepEqual(errors,[]);await page.unroute('**/api/decision');console.log('Mock browser checks passed: Play, two/five boards, exact inspector data, charts, hide/show, failure isolation, retry, Pause/Restart, touch and no overlap.');
 if(process.env.LIVE_JEV==='1'){await page.goto('http://127.0.0.1:2048');await page.getByText('Jev ready',{exact:true}).waitFor();await page.getByRole('tab',{name:'Compare',exact:true}).click();await page.locator('.policy-picker label').filter({hasText:'Strategy Jev'}).locator('input').check();const live=[];await page.route('**/api/decision',async route=>{const input=route.request().postDataJSON(),response=await route.fetch(),output=await response.json();if(response.ok()){assert.ok(legalMoves(input.board).includes(output.direction));assert.equal(output.model,'jev-1.13.0');assert.equal(output.evidence.policy,input.policy);live.push({policy:input.policy,model:output.model,usage:output.usage,direction:output.direction,ms:output.ms});}await route.fulfill({response});});await page.getByRole('combobox',{name:'Speed',exact:true}).selectOption('fast');await page.locator('#run').click();await page.waitForFunction(()=>['raw','strategy','feature','assisted'].every(id=>Number(document.querySelector('[data-testid='+id+'-moves]').textContent)>=3),null,{timeout:60000});await page.locator('#run').click();await idle();assert.equal(new Set(live.map(r=>r.policy)).size,4);await page.screenshot({path:'artifacts/lab-live-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:900});await page.screenshot({path:'artifacts/lab-live-desktop.png',fullPage:true});await page.getByRole('button',{name:'Inspect Expectimax-assisted Jev',exact:true}).click();await page.screenshot({path:'artifacts/lab-inspector-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('dialog').evaluate(e=>e.scrollWidth<=e.clientWidth),true);await page.screenshot({path:'artifacts/lab-inspector-mobile.png',fullPage:true});await writeFile('artifacts/lab-live-verification.json',JSON.stringify(live,null,2));console.log(JSON.stringify({liveCalls:live.length,policies:[...new Set(live.map(r=>r.policy))],model:live[0].model}));}
}finally{gate?.resolve();await browser.close();}
