import test from 'node:test';import assert from 'node:assert/strict';
import {reliableDecision,PausedDecision} from '../lib/reliability';import {MatchController,terminal,aggregate} from '../lib/match-controller';import {newGame,legalMoves} from '../public/engine.js';import {searchDecision,searchSummaries} from '../public/search-solver.js';import {policyEvidence,inspectAnswer} from '../decision-policies.js';
const g=newGame('unit-retry'),direction=legalMoves(g.board)[0],success={direction,probabilities:Object.fromEntries(legalMoves(g.board).map(d=>[d,d===direction?1:0])),ms:1,usage:{input_tokens:5,output_tokens:2},attempted:true};
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
const options={canStart:()=>true,onStatus:()=>{},onAttempt:()=>{},sleep:async()=>{}};
test('429 and temporary 503 use bounded exponential retries',async()=>{for(const status of [429,503]){let calls=0;const delays:number[]=[];const r=await reliableDecision({board:g.board},{...options,sleep:async ms=>{delays.push(ms);},fetcher:async()=>++calls<3?response({retryable:true},status):response(success)});assert.equal(r.direction,direction);assert.equal(calls,3);assert.deepEqual(delays,[400,800]);}});
test('actual abort timeout is retried without overlap',async()=>{let calls=0,active=0,max=0;const r=await reliableDecision({board:g.board},{...options,timeoutMs:5,fetcher:async(_url,init)=>{calls++;active++;max=Math.max(max,active);if(calls===1)await new Promise((_r,reject)=>init?.signal?.addEventListener('abort',()=>{active--;reject(Error('timeout'));}));active--;return response(success);}});assert.equal(r.direction,direction);assert.equal(calls,2);assert.equal(max,1);});
test('illegal choice gets exactly one corrected request, never applied',async()=>{const payloads:any[]=[];await reliableDecision({board:g.board},{...options,fetcher:async(_url,init)=>{payloads.push(JSON.parse(init?.body as string));return payloads.length===1?response({...success,direction:'diagonal'}):response(success);}});assert.equal(payloads.length,2);assert.equal(payloads[1].correction,true);let n=0;await assert.rejects(reliableDecision({board:g.board},{...options,fetcher:async()=>{n++;return response({...success,direction:'diagonal'});}}));assert.equal(n,2);});
test('exhaustion stops after four transient attempts; pause prevents retry',async()=>{let n=0;await assert.rejects(reliableDecision({board:g.board},{...options,fetcher:async()=>{n++;return response({retryable:true},503);}}));assert.equal(n,4);let allowed=true;n=0;await assert.rejects(reliableDecision({board:g.board},{...options,canStart:()=>allowed,sleep:async()=>{allowed=false;},fetcher:async()=>{n++;return response({retryable:true},429);}}),PausedDecision);assert.equal(n,1);});
const deferred=()=>{let resolve!:(v:any)=>void;const promise=new Promise<any>(r=>resolve=r);return {promise,resolve};};
const create=(jev?:any)=>new MatchController(()=>{},{jev,search:async b=>searchDecision(b)});
test('same-seed restart, single in-flight call, and stale response invalidation',async()=>{const gate=deferred();let calls=0;const m=create(async()=>{calls++;return gate.promise;});const initial=m.boards[1].game.board.slice();const old=m.boards[1],pending=m.tick(old);await m.tick(old);assert.equal(calls,1);m.reset();assert.deepEqual(m.boards[1].game.board,initial);gate.resolve({...success,direction:legalMoves(old.game.board)[0]});await pending;assert.equal(m.boards[1].game.moves,0);m.dispose();});
test('pause discards an in-flight result and prevents the next call',async()=>{const gate=deferred();let calls=0;const m=create(async()=>{calls++;return gate.promise;});m.speed='fast';m.run();m.pause();gate.resolve({...success,direction:legalMoves(m.boards[1].game.board)[0]});await new Promise(r=>setTimeout(r,15));assert.equal(m.boards[1].game.moves,0);assert.equal(calls,1);assert.equal(m.running,false);m.dispose();});
test('failure pauses only its board; other board continues; manual retry succeeds',async()=>{let fail=true;const m=create(async(payload:any)=>{if(fail)throw Error('Temporary failure');return {...success,direction:legalMoves(payload.board)[0]};});m.configure('compare',['raw','heuristic']);await m.step();assert.equal(m.boards[0].status,'API failure');assert.equal(m.boards[1].game.moves,1);await m.step();assert.equal(m.boards[1].game.moves,2);fail=false;await m.tick(m.boards[0],true);assert.equal(m.boards[0].game.moves,1);assert.equal(m.boards[0].error,'');m.dispose();});
test('2048 boards continue; only game-over boards freeze',async()=>{const m=create();m.configure('compare',['search','heuristic']);m.boards[0].game.board=[2048,...Array(15).fill(0)];m.status(m.boards[0]);await m.step();assert.equal(m.boards[0].status,'paused');assert.equal(m.boards[0].game.moves,1);assert.equal(terminal(m.boards[0]),false);assert.equal(m.boards[1].game.moves,1);m.boards[0].game.board=[2,4,2,4,4,2,4,2,2,4,2,4,4,2,4,2];m.status(m.boards[0]);await m.step();assert.equal(m.boards[0].status,'game over');assert.equal(m.boards[1].game.moves,2);m.dispose();});
test('raw, strategy, feature and assisted have distinct auditable inputs',()=>{const raw=policyEvidence(g.board,{},'raw'),strategy=policyEvidence(g.board,{},'strategy'),feature=policyEvidence(g.board,{},'feature'),assisted=policyEvidence(g.board,{},'assisted');assert.deepEqual(raw.state,strategy.state);assert.notEqual(raw.instruction,strategy.instruction);assert.equal('options' in raw.state,false);assert.ok((feature.state as Record<string,any>).options?.every((o:any)=>'monotonicity_penalty' in o));assert.deepEqual((assisted.state as Record<string,any>).options?.map((o:any)=>o.direction),legalMoves(g.board));assert.equal(JSON.stringify(assisted).includes('recommended_direction'),false);assert.equal(new Set([raw,strategy,feature,assisted].map(v=>v.model_requested)).size,1);});
test('search evidence ranks match pure solver without revealing its recommendation',()=>{const summaries=searchSummaries(g.board),pure=searchDecision(g.board);const best=summaries.slice().sort((a,b)=>b.expected_quality-a.expected_quality)[0];assert.equal(best.direction,pure.direction);assert.ok(summaries.every(s=>s.horizon_dead_end_probability>=0&&s.horizon_dead_end_probability<=1&&s.quality_standard_deviation>=0));});
test('Choice validation does not require unused optional confidence',()=>{assert.equal(inspectAnswer({answers:{direction:{type:'choice',choice:direction,probabilities:success.probabilities}}},legalMoves(g.board)).error,undefined);});
test('batch aggregation reports all games, median, variation and success rate',()=>{const m=create();m.configure('compare',['search','heuristic']);const rows=m.results();const chosen=rows.find(r=>r.policy==='search')!;chosen.score=100;chosen.reached=true;const a=aggregate([...rows,{...chosen,score:300,reached:false}]).find(r=>r.policy==='search')!;assert.equal(a.mean,200);assert.equal(a.median,200);assert.equal(a.reached,1);assert.equal(a.n,2);assert.ok(a.sd>0);m.dispose();});

 test('rounded 99 percent Choice distributions are valid and preserved',async()=>{const legal=legalMoves(g.board),p=Object.fromEntries(legal.map((d,i)=>[d,i<3?.33:0]));assert.equal(legal.length,4);const r={answers:{direction:{type:'choice',choice:legal[0],probabilities:p}}};assert.equal(inspectAnswer(r,legal).error,undefined);const result=await reliableDecision({board:g.board},{...options,fetcher:async()=>response({...success,probabilities:p})});assert.deepEqual(result.probabilities,p);assert.equal(inspectAnswer({answers:{direction:{...r.answers.direction,probabilities:Object.fromEntries(legal.map(d=>[d,.2]))}}},legal).error,'invalid_probabilities');});
import {TypeSafeClient} from '@typesafe-ai/sdk';
import {NextRequest} from 'next/server';
import {POST} from '../app/api/decision/route';
test('API accepts rounded distributions and continues Jev above 2048',async()=>{const original=TypeSafeClient.prototype.systemOne,saved=process.env.TYPESAFE_API_KEY;process.env.TYPESAFE_API_KEY='fake-test-only';try{for(const board of [g.board,[2048,2,...Array(14).fill(0)]]){const legal=legalMoves(board),p=legal.length===4?Object.fromEntries(legal.map((d,i)=>[d,i<3?.33:0])):Object.fromEntries(legal.map((d,i)=>[d,i===0?1:0]));TypeSafeClient.prototype.systemOne=(async()=>({model:'fake-test-model',answers:{direction:{type:'choice',choice:legal[0],probabilities:p}},usage:{input_tokens:3,output_tokens:1}})) as unknown as typeof original;const response=await POST(new NextRequest('http://localhost:2048/api/decision',{method:'POST',headers:{host:'localhost:2048'},body:JSON.stringify({board,score:0,moves:1000,match:crypto.randomUUID(),policy:'raw'})}));assert.equal(response.status,200);const body=await response.json();assert.deepEqual(body.probabilities,p);assert.equal(body.evidence.policy,'raw');}}finally{TypeSafeClient.prototype.systemOne=original;if(saved===undefined)delete process.env.TYPESAFE_API_KEY;else process.env.TYPESAFE_API_KEY=saved;}});
test('batch only advances after every board finishes and records both complete games',()=>{const m=create();m.configure('compare',['search','heuristic']);m.seed='batch-check/batch/1';m.batch={target:2,index:1,base:'batch-check',results:[]};const full=[2,4,2,4,4,2,4,2,2,4,2,4,4,2,4,2];m.boards[0].game.board=full;m.checkComplete();assert.equal(m.completedBatches.length,0);m.boards[1].game.board=full;m.checkComplete();assert.equal(m.completedBatches.length,2);assert.equal(m.seed,'batch-check/batch/2');assert.deepEqual(m.boards[0].game.board,m.boards[1].game.board);for(const b of m.boards)b.game.board=full;m.checkComplete();assert.equal(m.completedBatches.length,4);assert.equal(m.running,false);assert.ok(aggregate(m.completedBatches).every(r=>r.n===2));m.dispose();});
test('restart cannot overlap a still-finishing request for the same policy board',async()=>{const gate=deferred();let calls=0;const m=create(async(payload:any)=>{calls++;if(calls===1)return gate.promise;return {...success,direction:legalMoves(payload.board)[0]};});const old=m.boards[1],first=m.tick(old);m.reset();const second=m.tick(m.boards[1]);await new Promise(r=>setTimeout(r,1));assert.equal(calls,1);gate.resolve({...success,direction:legalMoves(old.game.board)[0]});await Promise.all([first,second]);assert.equal(calls,2);assert.equal(m.boards[1].game.moves,1);m.dispose();});

test('speed controls assisted Jev and local search without stopping other boards',async()=>{const m=create(async(payload:any)=>({...success,direction:legalMoves(payload.board)[0]}));m.configure('compare',['raw','assisted','heuristic','search']);m.setSpeed('fast');assert.deepEqual(m.boards.map(b=>m.speedFor(b)),['normal','fast','normal','fast']);m.setSpeed('step');m.run();await new Promise(r=>setTimeout(r,30));assert.equal(m.boards.find(b=>b.policy==='assisted')!.game.moves,0);assert.ok(m.boards.filter(b=>b.policy!=='assisted'&&b.policy!=='search').every(b=>b.game.moves>=1));assert.equal(m.running,true);m.pause();await m.step();assert.equal(m.boards.find(b=>b.policy==='assisted')!.game.moves,1);m.dispose();});
