import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame,move,legalMoves} from '../public/engine';
import {searchDecision} from '../public/search-solver';
import {resumeGame,validateBatch,type BatchInput,type BatchResult} from '../lib/local-batch';
import {runLocalBatch} from '../lib/local-batch-server';
import {MatchController} from '../lib/match-controller';
const input=():BatchInput=>{const g=newGame('ultra-unit');return {policy:'search',seed:'ultra-unit',board:g.board,score:0,moves:0,session:'unit',generation:1,sequence:1};};
function small(i:BatchInput):BatchResult{const g=resumeGame(i.seed,i.board,i.score,i.moves),records=[];for(let n=0;n<3;n++){const direction=legalMoves(g.board)[0];move(g,direction);records.push({direction,ms:1});}const final={board:g.board,score:g.score,moves:g.moves,highest:Math.max(...g.board)};return {...i,records,snapshots:[final],final,elapsedMs:4,computeMs:3,finished:false};}
test('Ultra resumes the exact existing random stream and validates replay',()=>{const i=input(),g=newGame(i.seed);for(let n=0;n<17;n++)move(g,legalMoves(g.board)[0]);const r=resumeGame(i.seed,g.board,g.score,g.moves);for(let n=0;n<12;n++){const d=legalMoves(g.board)[0];move(g,d);move(r,d);assert.deepEqual(r.board,g.board);assert.equal(r.score,g.score);}const result=small(i);validateBatch(i,result);assert.throws(()=>validateBatch(i,{...result,generation:99}));assert.throws(()=>validateBatch(i,{...result,final:{...result.final,score:999}}));});
test('server batch uses unchanged expectimax decisions and deterministic spawns for 100 moves',async()=>{const i=input(),result=await runLocalBatch(i,new AbortController().signal),g=newGame(i.seed);assert.equal(result.records.length,100);assert.deepEqual(result.snapshots.map(s=>s.moves),[50,100]);for(const r of result.records){assert.equal(r.direction,searchDecision(g.board).direction);move(g,r.direction);}assert.deepEqual(result.final.board,g.board);assert.equal(result.final.score,g.score);validateBatch(i,result);});
test('server yields and accepts cancellation between decisions',async()=>{const abort=new AbortController();const pending=runLocalBatch(input(),abort.signal);abort.abort();await assert.rejects(pending,{name:'AbortError'});});
test('Ultra batches only local policies; Step remains a single move and Jev keeps previous speed',async()=>{let batches=0;const m=new MatchController(()=>{},{search:async b=>searchDecision(b),localBatch:async i=>{batches++;return small(i);}});m.configure('compare',['search','assisted']);m.setSpeed('fast');m.setSpeed('ultra');assert.equal(m.speedFor(m.boards.find(b=>b.policy==='assisted')!),'fast');const local=m.boards.find(b=>b.policy==='search')!;await m.tick(local);assert.equal(local.game.moves,1);assert.equal(batches,0);m.running=true;await m.tick(local);m.pause();assert.equal(batches,1);assert.equal(local.game.moves,4);assert.equal(local.records.length,4);assert.equal(local.calls,0);m.dispose();});
test('Pause cancels batch; Restart rejects stale results without overlapping same policy',async()=>{for(const restart of [false,true]){let resolve!:(r:BatchResult)=>void,held!:BatchInput,signal!:AbortSignal,calls=0;const m=new MatchController(()=>{},{search:async b=>searchDecision(b),localBatch:async(i,s)=>{calls++;held=i;signal=s;return new Promise(r=>resolve=r);}});m.configure('play',['search']);m.setSpeed('ultra');m.running=true;const old=m.boards[1],pending=m.tick(old);await m.tick(old);assert.equal(calls,1);if(restart)m.reset();else m.pause();assert.equal(signal.aborted,true);resolve(small(held));await pending;assert.equal(m.boards[1].game.moves,0);assert.equal(old.game.moves,0);assert.equal(m.boards[1].error,'');m.dispose();}});
