import {readFileSync,writeFileSync,existsSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import {POLICIES,stats,mean,bootstrap,wilson} from './core.mjs';
function journal(file){if(!existsSync(file))return [];const lines=readFileSync(file,'utf8').split('\n'),out=[];for(let i=0;i<lines.length;i++){if(!lines[i])continue;try{out.push(JSON.parse(lines[i]));}catch{if(i===lines.length-1||lines[i+1]?.includes('"type":"recovered_partial_tail"'))continue;throw Error('Corrupt journal: '+file);}}return out;}
const labels={raw:'Raw Jev',strategy:'Strategy Jev',feature:'Feature Jev',assisted:'Expectimax-assisted Jev',heuristic:'Fixed heuristic',search:'Pure expectimax'};
const fmt=v=>v===null||v===undefined?'unavailable':typeof v==='number'?Number(v.toFixed(3)):v;
const csvCell=v=>'"'+String(v??'unavailable').replaceAll('"','""')+'"';
function svgChart(title,groups,unit){const colors=['#555d70','#a477da','#249fac','#e07a39','#64964f','#356acf'],max=Math.max(...groups.flatMap(g=>g.values),0)||1,width=960,height=360,left=180,plot=720;let s=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${title}"><rect width="100%" height="100%" fill="#faf9f5"/><g font-family="sans-serif" fill="#29313d"><text x="24" y="28" font-size="19">${title}</text>`;for(let i=0;i<=4;i++){const x=left+plot*i/4;s+=`<path d="M${x} 48V310" stroke="#d8d9da"/><text x="${x}" y="333" text-anchor="middle" font-size="12">${fmt(max*i/4)}</text>`;}groups.forEach((g,i)=>{const y=70+i*42;s+=`<text x="170" y="${y+4}" text-anchor="end" font-size="12">${labels[g.policy]}</text>`;if(!g.values.length)s+=`<text x="185" y="${y+4}" font-size="12">No complete games</text>`;g.values.forEach((v,j)=>{const x=left+plot*v/max;s+=`<circle cx="${x}" cy="${y+(j%5-2)*3}" r="5" fill="${colors[i]}" opacity=".65"><title>${labels[g.policy]}: ${fmt(v)} ${unit}</title></circle>`;});});return s+`<text x="540" y="354" text-anchor="middle" font-size="12">${unit}; each dot is one complete game</text></g></svg>`;}
function successChart(aggregate){let svg='<svg xmlns="http://www.w3.org/2000/svg" width="960" height="360" viewBox="0 0 960 360" role="img" aria-label="2048 success rate with 95 percent Wilson intervals"><rect width="100%" height="100%" fill="#faf9f5"/><g font-family="sans-serif" fill="#29313d"><text x="24" y="28" font-size="19">2048 success rate with 95% Wilson intervals</text>';for(let i=0;i<=4;i++){const x=210+650*i/4;svg+=`<path d="M${x} 45V312" stroke="#ddd"/><text x="${x}" y="334" text-anchor="middle">${i*25}%</text>`;}aggregate.forEach((r,i)=>{const y=65+i*43;svg+=`<text x="195" y="${y+5}" text-anchor="end" font-size="12">${labels[r.policy]}</text>`;if(!r.n){svg+=`<text x="220" y="${y+5}">No complete games</text>`;return;}const lo=210+650*r.success_2048_ci[0],hi=210+650*r.success_2048_ci[1],x=210+650*r.success_2048/r.n;svg+=`<path d="M${lo} ${y}H${hi}M${lo} ${y-6}V${y+6}M${hi} ${y-6}V${y+6}" stroke="#6b7890" stroke-width="2"/><circle cx="${x}" cy="${y}" r="6" fill="#356acf"><title>${r.success_2048}/${r.n} complete games</title></circle><text x="875" y="${y+5}" font-size="12">${r.success_2048}/${r.n}</text>`;});return svg+'</g></svg>';}
export function report(root){
 const m=JSON.parse(readFileSync(join(root,'manifest.json'))),rows=[];
 for(let i=0;i<m.seeds.length;i++)for(const policy of m.policies){const file=join(root,`${String(i+1).padStart(3,'0')}-${policy}.jsonl`),events=journal(file),result=events.filter(e=>e.type==='result').at(-1);if(result&&events.at(-1)?.type==='result')rows.push(result);else {const moves=events.filter(e=>e.type==='move'),attempts=events.filter(e=>e.type==='attempt'),last=moves.at(-1),input=attempts.reduce((s,e)=>s+(e.usage?.input_tokens||0),0),output=attempts.reduce((s,e)=>s+(e.usage?.output_tokens||0),0);rows.push({id:`${i+1}-${policy}`,seed:m.seeds[i],policy,terminal_status:events.length?'in_progress_or_interrupted':'not_started',final_score:last?.score??null,highest_tile:last?.highest??null,total_moves:last?.move??0,first_2048_move:moves.find(t=>t.highest>=2048)?.move??null,first_4096_move:moves.find(t=>t.highest>=4096)?.move??null,reached_2048:moves.some(t=>t.highest>=2048),reached_4096:moves.some(t=>t.highest>=4096),latency_ms:stats(moves.map(t=>t.latency_ms)),jev_calls:attempts.length,input_tokens:input,output_tokens:output,unknown_usage_calls:attempts.filter(e=>!e.usage).length,estimated_cost_usd:(input*m.config.input_price+output*m.config.output_price)/1e6,transient_retries:events.filter(e=>e.type==='retry').length,model_version:[...new Set(attempts.map(e=>e.model).filter(Boolean))],policy_hash:m.policy_hash});}}
 const complete=rows.filter(r=>r.terminal_status==='game_over'),incomplete=rows.filter(r=>r.terminal_status!=='game_over');
 const columns=['seed','policy','terminal_status','final_score','highest_tile','total_moves','reached_2048','first_2048_move','reached_4096','first_4096_move','latency_mean_ms','latency_median_ms','latency_p95_ms','jev_calls','input_tokens','output_tokens','unknown_usage_calls','estimated_cost_usd','transient_retries','model_version','policy_hash','agreement_rate','highest_value_rate','disagreements','failure'];
 writeFileSync(join(root,'summary.csv'),[columns.join(','),...rows.map(r=>columns.map(c=>csvCell(c==='model_version'?r[c]?.join(';'):c.startsWith('latency_')?r.latency_ms?.[c.split('_')[1]]:r[c])).join(','))].join('\n'));
 const aggregate=POLICIES.map(policy=>{const a=complete.filter(r=>r.policy===policy),scores=a.map(r=>r.final_score);return {policy,n:a.length,score:stats(scores),score_mean_ci:bootstrap(scores),success_2048:a.filter(r=>r.reached_2048).length,success_2048_ci:wilson(a.filter(r=>r.reached_2048).length,a.length),success_4096:a.filter(r=>r.reached_4096).length,latency_ms:stats(a.map(r=>r.latency_ms.mean)),calls:a.reduce((s,r)=>s+r.jev_calls,0),input:a.reduce((s,r)=>s+r.input_tokens,0),output:a.reduce((s,r)=>s+r.output_tokens,0),cost:a.reduce((s,r)=>s+r.estimated_cost_usd,0)};});
 const pairs=[];for(let i=0;i<POLICIES.length;i++)for(let j=i+1;j<POLICIES.length;j++){const a=POLICIES[i],b=POLICIES[j],matched=m.seeds.flatMap(seed=>{const x=complete.find(r=>r.seed===seed&&r.policy===a),y=complete.find(r=>r.seed===seed&&r.policy===b);return x&&y?[{seed,score_difference:x.final_score-y.final_score,success_difference:Number(x.reached_2048)-Number(y.reached_2048)}]:[];});pairs.push({a,b,n:matched.length,mean_score_difference:mean(matched.map(r=>r.score_difference)),score_ci:bootstrap(matched.map(r=>r.score_difference)),mean_success_difference:mean(matched.map(r=>r.success_difference)),success_ci:bootstrap(matched.map(r=>r.success_difference)),seeds:matched});}
 writeFileSync(join(root,'statistics.json'),JSON.stringify({aggregate,pairs,incomplete},null,2));
 for(const [name,title,unit,get] of [['scores','Score distribution','score',r=>r.final_score],['highest-tiles','Highest-tile distribution','tile value',r=>r.highest_tile],['success','2048 success by complete game','0 = not reached; 1 = reached',r=>Number(r.reached_2048)],['latency','Mean decision latency per game','milliseconds',r=>r.latency_ms.mean],['tokens','Reported input tokens per game','input tokens',r=>r.input_tokens],['cost','Estimated Jev cost per game','USD',r=>r.estimated_cost_usd]])writeFileSync(join(root,name+'.svg'),svgChart(title,POLICIES.map(policy=>({policy,values:complete.filter(r=>r.policy===policy).map(get)})),unit));
 writeFileSync(join(root,'success.svg'),successChart(aggregate));
 writeFileSync(join(root,'output-tokens.svg'),svgChart('Reported output tokens per game',POLICIES.map(policy=>({policy,values:complete.filter(r=>r.policy===policy).map(r=>r.output_tokens)})),'output tokens'));
 const total=rows.reduce((s,r)=>({calls:s.calls+(r.jev_calls||0),input:s.input+(r.input_tokens||0),output:s.output+(r.output_tokens||0),cost:s.cost+(r.estimated_cost_usd||0),unknown:s.unknown+(r.unknown_usage_calls||0)}),{calls:0,input:0,output:0,cost:0,unknown:0});
 const sessions=journal(join(root,'events.jsonl'));let wall=0,openSession=null;for(const event of sessions){if(event.type==='session_start')openSession=Date.parse(event.at);if(event.type==='session_end'){wall+=event.elapsed_ms;openSession=null;}}if(openSession!==null)wall+=Math.max(0,Date.now()-openSession);
 const allComplete=complete.length===m.seeds.length*POLICIES.length,factor=20/m.seeds.length,forecast={basis_complete_games:complete.length,expected_full_games:120,expected_calls:Math.ceil(total.calls*factor),expected_input_tokens:Math.ceil(total.input*factor),expected_output_tokens:Math.ceil(total.output*factor),estimated_cost_usd:total.cost*factor,minimum_rate_limited_minutes:Math.ceil(total.calls*factor)/Math.min(m.config.rpm/60,Math.floor(m.config.tps/(m.config.reservation||32768)))/60,runtime_minutes_ideal_concurrency_4:Math.max(wall/60000*factor*m.config.concurrency/4,Math.ceil(total.calls*factor)/Math.min(m.config.rpm/60,Math.floor(m.config.tps/(m.config.reservation||32768)))/60),runtime_minutes_same_throughput:wall/60000*factor,all_pilot_games_complete:allComplete,warning:'Linear planning estimate from only two seeds. Long-lived games, retries, provider variability and CPU contention may increase runtime and spend; missing usage makes cost a lower bound.'};
 writeFileSync(join(root,'forecast-20-seeds.json'),JSON.stringify(forecast,null,2));
 let md=`# 2048 decision-support study\n\nDate: ${m.date}. Phase: **${m.phase}**. Model: **${m.config.model}**. Policy/source hash: \`${m.policy_hash}\`.\n\n${complete.length}/${rows.length} complete games. ${incomplete.length} incomplete or not started, excluded from scores and success-rate denominators.\n\n## Setup\n\nAll six unchanged policies use the same ${m.seeds.length} pre-generated seeds in manifest.json. Each game has independent seeded randomness. Seeds share starts, not identical later tile positions. Jev is not guaranteed deterministic. Stop only at true game over; record 2048 and 4096 milestones and continue. No move or call cap. Concurrency ${m.config.concurrency}. Each Jev game awaits its response before its next request.\n\nRaw: board, legal moves, rules, goal. Strategy: adds written principles. Feature: calculated immediate outcomes. Assisted: bounded three-player-ply search with two random-spawn layers, 90/10 spawn weights, probability cutoff 0.0001, comparable summaries, no recommended direction. All use the same pinned Jev model and unchanged prompts. Fixed heuristic uses weighted immediate board features without search. Pure expectimax chooses the highest bounded-search value, without Jev. MIT attribution: [nneonneo](../../public/licenses/nneonneo-MIT.txt).\n\nPolicies and runner sources are snapshotted under frozen/ and hashed before execution. Pilot/tuning/evaluation seed namespaces are distinct. No tuning against evaluation seeds.\n\n## Results\n\n| Policy | Complete | Mean score | Median | Sample SD | Range | 95% bootstrap mean CI | 2048 | 95% Wilson success CI | 4096 | Mean decision ms | Calls | Input tokens | Output tokens | USD |\n|---|---:|---:|---:|---:|---|---|---:|---|---:|---:|---:|---:|---:|---:|\n`;
 for(const r of aggregate)md+=`| ${labels[r.policy]} | ${r.n} | ${fmt(r.score.mean)} | ${fmt(r.score.median)} | ${fmt(r.score.sd)} | ${fmt(r.score.min)}–${fmt(r.score.max)} | ${r.score_mean_ci.map(fmt).join(' to ')} | ${r.success_2048}/${r.n} | ${r.success_2048_ci.map(v=>v===null?'unavailable':(v*100).toFixed(1)+'%').join(' to ')} | ${r.success_4096}/${r.n} | ${fmt(r.latency_ms.mean)} | ${r.calls} | ${r.input} | ${r.output} | ${r.cost.toFixed(6)} |\n`;
 md+=`\nTotal including incomplete runs: ${total.calls} calls, ${total.input} reported input tokens, ${total.output} reported output tokens, $${total.cost.toFixed(6)} estimated. Unknown usage on ${total.unknown} calls. Session wall time: ${(wall/60000).toFixed(1)} minutes. Price assumptions: $${m.config.input_price}/M input and $${m.config.output_price}/M output, [TypeSafe models](https://docs.typesafe.ai/models). Not an invoice; unknown usage is not zero cost.\n\n## Charts\n\n`;
 for(const name of ['scores','highest-tiles','success','latency','tokens','output-tokens','cost'])md+=`![${name}](${name}.svg)\n\n`;
 md+='## Paired comparisons\n\nPaired by starting seed, using only pairs with both games complete. These are differences over repeatable starts, not identical random tile outcomes or matched trajectories. Bootstrap resamples whole seed pairs (2,000 replicates, fixed PRNG seed). Intervals are exploratory, not corrected for multiple comparisons, and two-seed intervals are especially unstable.\n\n| A minus B | Pairs | Mean score difference | 95% bootstrap CI | Mean 2048-rate difference | 95% bootstrap CI |\n|---|---:|---:|---|---:|---|\n';
 for(const p of pairs)md+=`| ${labels[p.a]} minus ${labels[p.b]} | ${p.n} | ${fmt(p.mean_score_difference)} | ${p.score_ci.map(fmt).join(' to ')} | ${fmt(p.mean_success_difference)} | ${p.success_ci.map(fmt).join(' to ')} |\n`;
 md+='\n## Assisted Jev audit\n\nEvery assisted move journal includes the exact presented summaries and probability distribution, pure expectimax root values calculated separately on the same board, deterministic tie-broken agreement, and whether the selected move had the highest root value. The audit is never passed to Jev. High agreement indicates that search summaries largely determine the observed choices; it is not evidence of independent planning by Jev. Every disagreement is retained. Its board-quality change is best bounded-search value after the actual spawn minus best value before the move. This mixes move and random-spawn effects, changes the search horizon origin, and is not a causal measure of decision quality. Ties are distinguished from disagreement. Audit CPU time is recorded separately and excluded from decision latency.\n\n';
 for(const r of complete.filter(r=>r.policy==='assisted'))md+=`- ${r.seed}: agreement ${(100*r.agreement_rate).toFixed(1)}%, selected highest value ${(100*r.highest_value_rate).toFixed(1)}%, ${r.disagreements} disagreements.\n`;
 const assistedRows=complete.filter(r=>r.policy==='assisted'),assistedMoves=assistedRows.reduce((s,r)=>s+r.total_moves,0),disagreements=assistedRows.reduce((s,r)=>s+r.disagreements,0),belowBest=assistedRows.reduce((s,r)=>s+Math.round(r.total_moves*(1-r.highest_value_rate)),0);if(assistedMoves)md+=`\nAcross ${assistedMoves} assisted decisions, ${disagreements} differed from the deterministic preferred direction. ${disagreements-belowBest} were highest-value ties (within 1e-8); ${belowBest} selected a lower search value. Agreement was ${(100*(assistedMoves-disagreements)/assistedMoves).toFixed(2)}%. These counts describe the supplied-value comparison, not hidden reasoning.\n`;
 md+='\n## Incomplete / failed runs\n\n';md+=incomplete.length?incomplete.map(r=>`- ${r.seed}, ${labels[r.policy]}: ${r.terminal_status}; ${r.failure||'no terminal result'}.`).join('\n'):'None.';
 md+=`\n\n## Limits and interpretation\n\nDecision latency includes feature construction, rate-limit waiting, API time and retries; local policies measure their calculation. Added assisted-audit work and disk writes are excluded but can cause shared-process contention. This runner uses concurrent independent games in one Node process, not isolated CPU benchmarking. Per-game latency mean, median and p95 are in CSV. Missing usage is explicit. Three transient retries use exponential backoff and Retry-After when available; exhaustion means incomplete, never loss or fallback. Limiting is shared within this runner only, not across other applications using the key. The conservative 32,768-token reservation covers each single-question context budget; configured limits are ${m.config.rpm} requests/min and ${m.config.tps} tokens/sec. Account limits may change.\n\nFrozen seed streams reproduce code randomness, not model responses or network timing. Existing historical experiments remain separate. A small pilot estimates feasibility and cost, not superiority.\n\n## 20-seed planning estimate\n\n${allComplete?'All pilot games completed.':'Provisional: some games are incomplete.'} Linear projection: ${forecast.expected_calls} calls, ${forecast.expected_input_tokens} input tokens, ${forecast.expected_output_tokens} output tokens, $${forecast.estimated_cost_usd.toFixed(4)}. Optimistic concurrency-4 runtime including the configured rate floor: ${forecast.runtime_minutes_ideal_concurrency_4.toFixed(1)} minutes; at observed throughput ${forecast.runtime_minutes_same_throughput.toFixed(1)} minutes. The reservation limiter alone requires at least ${forecast.minimum_rate_limited_minutes.toFixed(1)} minutes for the projected calls; doubling concurrency does not double throughput at that limit. These are estimates, not completion guarantees. No full paid run was started automatically.\n`;
 writeFileSync(join(root,'REPORT.md'),md);return {total,forecast,complete:complete.length,incomplete:incomplete.length};
}
