'use client';
import {useEffect,useRef,useState} from 'react';
import {X,ChevronLeft,ChevronRight} from 'lucide-react';
import {MiniBoard,arrows} from './board';
import {botName} from '@/lib/play-options';
import {historicalMove,findHistoricalEvent} from '@/lib/analytics-history';
import {DETAIL_LIMIT,POINT_LIMIT,stageLabels} from '@/lib/turn-analytics';
import type {LabBoard,LabDecision} from '@/lib/match-controller';
import EvidenceGuide from './evidence-guide';
import TimingFigure from './timing-figure';
const pct=(n:number|null|undefined)=>n==null?'Unavailable':(100*n).toFixed(1)+'%';
const agreed=(b:boolean|null|undefined)=>b==null?'Unavailable':b?'Yes':'No';
export default function DecisionInspector({board,onClose}:{board:LabBoard;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[selected,setSelected]=useState<number|null>(null),[archived,setArchived]=useState<LabDecision|null>(null),[tab,setTab]=useState('boards'),[jump,setJump]=useState('score'),[message,setMessage]=useState(''),[failureMessage,setFailureMessage]=useState('');
 useEffect(()=>{dialog.current?.showModal();return ()=>dialog.current?.close();},[]);
 useEffect(()=>{let live=true;setArchived(null);if(selected!==null&&!board.records.some(r=>r.move===selected)){setMessage('Loading stored move…');void historicalMove(board.id,selected).then(r=>{if(live){setArchived(r);setMessage(r?'':'This move is not available in local history.');}}).catch(()=>{if(live)setMessage('Local history is unavailable.');});}else setMessage('');return ()=>{live=false};},[selected,board.id]);
 const r=selected===null?board.records[0]:board.records.find(r=>r.move===selected)??archived,a=r?.analytics,e=r?.evidence as any,candidates=a?.candidates??[],audit=e?.audit_not_sent;
 async function jumpTo(){setFailureMessage('');if(jump==='errors'){const failure=board.failures[0];if(failure){setSelected(Math.max(1,failure.move-1));setFailureMessage('Failed attempt at move '+failure.move+': '+failure.category+'. No move was applied.');}else setMessage('No recorded request errors.');return;}const recent=board.records.find(r=>{const a=r.analytics;return a&&(jump==='score'?a.scoreIncrease>=128:jump==='confidence'?a.margin!==null&&a.margin<.1:jump==='override'?a.overridesSearch||a.overridesLearned:a.gameOver);});if(recent){setSelected(recent.move);setMessage('');return;}try{const found=await findHistoricalEvent(board.id,jump);if(found)setSelected(found);else setMessage('No matching move in this match.');}catch{setMessage('Older history is unavailable.');}}
 return <dialog ref={dialog} className="decision-dialog analytics-inspector" aria-labelledby="inspector-title" onCancel={onClose}><div className="inspector-head"><div><h2 id="inspector-title">Inspect</h2><p>{botName(board.policy)} · live session history</p></div><button aria-label="Close inspector" onClick={onClose}><X/></button></div>
 <div className="move-navigation"><button aria-label="Previous move" disabled={!r||r.move<=1} onClick={()=>setSelected(r!.move-1)}><ChevronLeft/></button><label>Move <input aria-label="Inspect move number" type="number" min={1} max={board.game.moves||1} value={r?.move??''} onChange={ev=>{const n=Number(ev.target.value);if(n>=1&&n<=board.game.moves)setSelected(n)}}/></label><span>of {board.game.moves}</span><button aria-label="Next move" disabled={!r||r.move>=board.game.moves} onClick={()=>setSelected(r!.move+1)}><ChevronRight/></button><button onClick={()=>setSelected(null)}>Latest</button><select aria-label="Jump to event" value={jump} onChange={ev=>setJump(ev.target.value)}><option value="score">Score gain ≥ 128</option><option value="confidence">Probability margin &lt; 0.10</option><option value="override">Expert disagreement</option><option value="errors">Request errors</option><option value="end">Game-ending move</option></select><button onClick={()=>void jumpTo()}>Find latest</button></div>
 {message&&<p role="status">{message}</p>}{failureMessage&&<p role="status">{failureMessage}</p>}{board.archiveError&&<p role="alert">{board.archiveError}</p>}
 {!r?<p className="inspector-empty">No move yet. Press Step to inspect one.</p>:<><div className="move-summary"><strong>{arrows[r.direction]} {r.direction}</strong><span>+{r.gain} points</span><span>Score {a?.score.toLocaleString()??'Unavailable'}</span><span>{a?.timestamp?new Date(a.timestamp).toLocaleTimeString():''}</span><span>{r.model??'Local bot'} · {a?.schemaVersion??'Schema version unavailable'}</span></div>
 <div className="inspect-tabs" role="tablist" aria-label="Move details">{[['boards','Boards and choice'],['analytics','Probabilities and timing'],['evidence','Supplied information']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='boards'&&<section role="tabpanel"><div className="move-boards"><article><h3>Board before move</h3><MiniBoard board={r.before}/><p>{a?.emptyBefore} empty cells · {a?.mergesBefore} available merges</p></article><article><h3>Chosen outcome</h3><MiniBoard board={r.preSpawn}/><p>{a?.selectedCandidate?'Candidate '+a.selectedCandidate+' · ':''}+{r.gain} reward, before spawning</p></article><article><h3>Board after spawn</h3><MiniBoard board={r.after} highlight={r.spawn.index}/><p>New {r.spawn.value} at row {Math.floor(r.spawn.index/4)+1}, column {r.spawn.index%4+1}</p></article></div><p className="lab-note">Legal directions: {a?.legal.join(', ')??'Unavailable'}. Available merges means the maximum merges in one legal move.</p>
 {!!candidates.length&&<><h3>Available candidate boards</h3><p className="lab-note">Labels were shuffled. Direction mapping is revealed here only after the move.</p><div className="anonymous-options">{candidates.map(c=><article key={c.label} className={c.label===a?.selectedCandidate?'chosen':''}><h4>Candidate {c.label}{c.label===a?.selectedCandidate?' · selected':''}</h4><MiniBoard board={c.board}/><p>{c.direction} · +{c.reward} points</p><p>{pct(c.probability)} preference</p></article>)}</div></>}
 <dl className="move-facts"><div><dt>Seed</dt><dd>{a?.seed??'Unavailable'}</dd></div><div><dt>Spawn sequence</dt><dd>{a?.spawn.sequence??'Unavailable'} (including the two starting tiles)</dd></div><div><dt>Random draw offset</dt><dd>{a?.spawn.randomDrawOffset??'Unavailable'} (zero-based)</dd></div><div><dt>Highest tile</dt><dd>{a?.highest.toLocaleString()??'Unavailable'}</dd></div><div><dt>Empty cells</dt><dd>{a?.emptyBefore} → {a?.emptyAfter}</dd></div><div><dt>Available merges</dt><dd>{a?.mergesBefore} → {a?.mergesAfter}</dd></div><div><dt>Legal next moves</dt><dd>{a?.legalNext.join(', ')||'None'}</dd></div><div><dt>Game ended</dt><dd>{a?.gameOver?'Yes':'No'}</dd></div></dl></section>}
 {tab==='analytics'&&<section role="tabpanel"><div className="turn-metrics"><div><span>Selected probability</span><strong>{pct(a?.selectedProbability)}</strong></div><div><span>Top-two margin</span><strong>{a?.margin==null?'Unavailable':a.margin.toFixed(3)}</strong></div><div><span>Entropy, calculated locally</span><strong>{a?.entropyBits==null?'Unavailable':a.entropyBits.toFixed(3)+' bits'}</strong></div></div><p>These probabilities show Jev’s preference among the supplied candidates. They are not win probabilities.</p>
 {candidates.map(c=><div className="inspector-prob" key={c.label}><span>{c.label}</span><meter min={0} max={1} value={c.probability??0} aria-label={'Candidate '+c.label+' probability'}/><b>{pct(c.probability)}</b></div>)}
 <p className="lab-note">Margin is the highest minus second-highest probability, not move quality. Entropy normalizes the reported probability mass before calculating −Σ p log₂ p. Candidate order: {a?.candidateOrder.join(', ')||'Not applicable'}; {a?.ordering??'unavailable'}. Reversed-order testing was not performed for this live move.</p>
 <h3>Specialist comparison</h3><p className="lab-note">Values appear only when supplied to this Jev version. Ranks are calculated here afterward and were not sent to Jev. Agreement is not correctness; an override is a disagreement, not an improvement. Audits: {audit?.status??'unavailable'}.</p>
 <div className="lab-table-scroll"><table><thead><tr><th>Candidate</th><th>Jev probability</th><th>Search value / rank</th><th>Learned value / rank</th><th>Reward</th><th>Selected by</th></tr></thead><tbody>{candidates.map(c=><tr key={c.label}><th>{c.label} · {c.direction}</th><td>{pct(c.probability)}</td><td>{c.searchValue===null?'Not supplied':c.searchValue.toFixed(4)+' / '+c.searchRank}</td><td>{c.learnedValue===null?'Not supplied':c.learnedValue.toFixed(4)+' / '+c.learnedRank}</td><td>+{c.reward}</td><td>{[a?.selectedCandidate===c.label?'Jev':null,audit?.expectimax_preferred===c.direction?'Expectimax':null,audit?.ntuple_preferred===c.direction?'N-tuple':null].filter(Boolean).join(', ')||'None recorded'}</td></tr>)}</tbody></table></div>
 <div className="agreement-summary"><span>Agreed with expectimax: <b>{agreed(a?.agreesSearch)}</b></span><span>Agreed with n-tuple: <b>{agreed(a?.agreesLearned)}</b></span></div><h3>Decision timing</h3>{a&&<TimingFigure timing={a.timing}/>}<p className="lab-note">{a?.timingScope}</p><dl className="move-facts"><div><dt>Input / output tokens, all attempts</dt><dd>{a?.inputTokens??'Unavailable'} / {a?.outputTokens??'Unavailable'}</dd></div><div><dt>HTTP attempts / retries</dt><dd>{a?.attempts??'Unavailable'} / {a?.retries??'Unavailable'}</dd></div><div><dt>Error category</dt><dd>{a?.errorCategory??'None recorded'}</dd></div><div><dt>Estimated cost</dt><dd>Unavailable: no configured official price</dd></div></dl></section>}
 {tab==='evidence'&&<section role="tabpanel"><h3>Information sent to Jev</h3><p>{e?.exact_request?'This is the sanitized request for this move. Candidate labels and ordering are preserved. Direction mapping and audit preferences were not included.':'This local bot did not send a Jev request. Recorded calculation output appears below.'}</p><EvidenceGuide evidence={e?.exact_request?.state}/><pre>{JSON.stringify(e?.exact_request??e??{},null,2)}</pre>{candidates.length>0&&<details><summary>Calculated evidence by candidate</summary>{candidates.map(c=><div key={c.label}><h4>Candidate {c.label}</h4><pre>{JSON.stringify(c.evidence,null,2)}</pre></div>)}</details>}<p>These records show supplied information and observable outputs, not Jev’s private reasoning.</p></section>}
 </>}
 <details className="history-note"><summary>History storage</summary><p>Memory retains the latest {DETAIL_LIMIT} detailed moves and {POINT_LIMIT.toLocaleString()} numeric points per board, across at most five boards. Evidence is limited to 65,536 serialized characters per move and shared request definitions are stored once. Older moves are read on demand from this browser’s IndexedDB archive. Restart removes the prior board’s history. Storage failure is reported; it never changes gameplay. Charts use windows of up to {POINT_LIMIT.toLocaleString()} moves and keep flagged events within each window. Up to three specialist audits can run at once; a busy audit is marked unavailable.</p></details>
 </dialog>;
}
