'use client';
import {useEffect,useRef,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
import {botName,botColor} from '@/lib/play-options';import {downsample,POINT_LIMIT,timingParts,agreementCounts,type NumericTurn} from '@/lib/turn-analytics';
import {historicalWindow,currentWindow,type ChartRow} from '@/lib/analytics-history';import type {LabBoard} from '@/lib/match-controller';
const measures={score:'Score by move',time:'Decision time by move',composition:'Timing composition',confidence:'Jev confidence outputs',agreement:'Agreement over time',api:'API use and disagreements'};
export default function LabCharts({boards}:{boards:LabBoard[]}){
 const [open,setOpen]=useState(false),[view,setView]=useState<keyof typeof measures>('score'),[bot,setBot]=useState('all'),[range,setRange]=useState<number|null>(null),[rows,setRows]=useState<Record<string,ChartRow[]>>({}),[notice,setNotice]=useState('');const live=useRef(boards);live.current=boards;const ids=boards.map(b=>b.id).join(',');
 useEffect(()=>{if(!open)return;let cancelled=false,busy=false;async function update(){if(busy)return;busy=true;const next:Record<string,ChartRow[]>={};for(const b of live.current){const end=range===null?b.game.moves:Math.min(b.game.moves,range+POINT_LIMIT-1),start=range??Math.max(1,end-POINT_LIMIT+1);try{if(range===null||start>=b.points[0]?.move){next[b.id]=currentWindow(b.points.flatMap(p=>p.analytics&&p.move>=start&&p.move<=end?[p.analytics]:[]));}else next[b.id]=await historicalWindow(b.id,start,end);}catch{next[b.id]=[];if(!cancelled)setNotice('Older chart history is unavailable.');}}if(!cancelled)setRows(next);busy=false;}void update();const timer=setInterval(()=>void update(),750);return ()=>{cancelled=true;clearInterval(timer)};},[open,range,ids]);
 const visible=boards.filter(b=>!b.hidden&&(bot==='all'||bot===b.id)),first=visible.find(b=>b.policy.startsWith('blind-'))??visible[0],chosen=first?rows[first.id]??[]:[],max=Math.max(0,...visible.map(b=>b.game.moves));
 const lineRows=(()=>{const map=new Map<number,any>();for(const b of visible)for(const row of downsample(rows[b.id]??[])){const data=map.get(row.move)??{move:row.move};data[b.id]=view==='time'?row.timing.total.ms:row.score;map.set(row.move,data);}return [...map.values()].sort((a,b)=>a.move-b.move);})();
 const outputs=downsample(chosen).map(r=>({move:r.move,selected:r.selectedProbability,margin:r.margin,entropy:r.entropyBits,search:r.cumulative.searchKnown?r.cumulative.searchAgreed/r.cumulative.searchKnown:null,learned:r.cumulative.learnedKnown?r.cumulative.learnedAgreed/r.cumulative.learnedKnown:null,both:r.cumulative.bothKnown?r.cumulative.both/r.cumulative.bothKnown:null,neither:r.cumulative.bothKnown?r.cumulative.neither/r.cumulative.bothKnown:null}));
 const parts=['Local preparation','Native model work','Jev HTTP wait','Parsing','Other / unisolated overhead'],colors=['#b96325','#087c79','#bd365d','#7746b5','#8b7b92'];const compositions=visible.map(b=>{const timed=(rows[b.id]??[]).filter(r=>r.timing.total.ms!==null);return {name:botName(b.policy),n:timed.length,...Object.fromEntries(parts.map((p,i)=>[p,timed.length?timed.reduce((s,r)=>s+timingParts(r.timing)[i].ms,0)/timed.length:null]))};}).filter(r=>r.n);
 return <details className="match-analytics" onToggle={e=>setOpen(e.currentTarget.open)}><summary>Match analytics <span>Scores, timing, Jev outputs and API use</span></summary>{open&&<div className="analytics-body"><div className="analytics-toolbar"><label>View <select aria-label="Analytics view" value={view} onChange={e=>setView(e.target.value as any)}>{Object.entries(measures).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Bot <select aria-label="Analytics bot" value={bot} onChange={e=>setBot(e.target.value)}><option value="all">All visible bots</option>{boards.map(b=><option key={b.id} value={b.id}>{botName(b.policy)}</option>)}</select></label><label>From move <input type="number" aria-label="Chart first move" min={1} max={Math.max(1,max)} placeholder="Latest" value={range??''} onChange={e=>setRange(e.target.value?Math.max(1,Number(e.target.value)):null)}/></label><button onClick={()=>setRange(null)}>Latest window</button></div><p className="lab-note">Live session data, separate from saved research results. Up to {POINT_LIMIT.toLocaleString()} moves per view. Flagged events stay visible when ordinary points are downsampled. Older complete numeric records are read from local storage.</p>{notice&&<p>{notice}</p>}
 {(view==='score'||view==='time')&&(lineRows.length?<><ResponsiveContainer width="100%" height={300} minWidth={0}><LineChart data={lineRows} margin={{top:15,right:15,left:0,bottom:25}} accessibilityLayer><CartesianGrid vertical={false} stroke="#d8c4a6"/><XAxis dataKey="move" type="number" domain={['dataMin','dataMax']} allowDecimals={false} label={{value:'Move number',position:'insideBottom',offset:-15}}/><YAxis width={65} tick={{fontSize:12}}/><Tooltip labelFormatter={v=>'Move '+v} formatter={(v:any,n:any)=>[v==null?'Unavailable':Number(v).toLocaleString(undefined,{maximumFractionDigits:2})+(view==='time'?' ms':''),n]}/><Legend wrapperStyle={{fontSize:12}}/>{visible.map(b=><Line key={b.id} dataKey={b.id} name={botName(b.policy)} stroke={botColor(b.policy)} strokeWidth={2.3} dot={lineRows.length<20} isAnimationActive={false} connectNulls={false}/>)}</LineChart></ResponsiveContainer><p>{view==='score'?'Score is aligned by move number. It measures game progress, not execution speed.':'Raw end-to-end decision time in milliseconds, excluding deferred audit and UI delay. Per-move Ultra end-to-end time is unavailable.'}</p></>:<p className="analytics-empty">Make a move to start the chart.</p>)}
 {view==='composition'&&(compositions.length?<><ResponsiveContainer width="100%" height={300} minWidth={0}><BarChart data={compositions} margin={{top:15,right:10,left:0,bottom:10}} accessibilityLayer><CartesianGrid vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis width={65} label={{value:'ms',position:'insideTopLeft'}}/><Tooltip formatter={(v:any,n:any)=>[Number(v)>0?Number(v).toFixed(2)+' ms':'Not isolated / not used',n]}/>{parts.map((p,i)=><Bar key={p} dataKey={p} stackId="time" fill={colors[i]} isAnimationActive={false}/>)}</BarChart></ResponsiveContainer><div className="timing-legend">{parts.map((p,i)=><span key={p}><i style={{background:colors[i]}}/>{p}</span>)}</div><p>Mean composition in the displayed window. Unknown stages remain in overhead; audit and UI delay are excluded. {compositions.map(r=>r.name+': n = '+r.n).join('; ')}.</p></>:<p>No isolated end-to-end timings in this window.</p>)}
 {(view==='confidence'||view==='agreement')&&<><p>{first?botName(first.policy):'Choose a Jev bot'} · {chosen.length} recorded moves. {view==='confidence'?'Classifier outputs, not move quality. Entropy uses the right axis in bits.':'Cumulative within the displayed range. Unavailable audits are excluded from each denominator. Agreement does not establish correctness.'}</p>{outputs.length>0?<ResponsiveContainer width="100%" height={300} minWidth={0}><LineChart data={outputs} margin={{top:15,right:15,left:0,bottom:25}} accessibilityLayer><CartesianGrid vertical={false}/><XAxis dataKey="move" type="number" domain={['dataMin','dataMax']} label={{value:'Move number',position:'insideBottom',offset:-15}}/><YAxis domain={[0,1]} tickFormatter={v=>(v*100)+'%'} width={50}/>{view==='confidence'&&<YAxis yAxisId="entropy" orientation="right" domain={[0,2]} width={40} label={{value:'bits',position:'insideTopRight'}}/>}<Tooltip labelFormatter={v=>'Move '+v}/><Legend wrapperStyle={{fontSize:12}}/>{(view==='confidence'?[['selected','Selected probability','#bd365d'],['margin','Top-two margin','#395eb2'],['entropy','Entropy (bits)','#087c79']]:[['search','Agreed with expectimax','#7746b5'],['learned','Agreed with n-tuple','#087c79'],['both','Agreed with both','#b96325'],['neither','Agreed with neither','#bd365d']]).map(([key,name,color])=><Line key={key} dataKey={key} yAxisId={key==='entropy'?'entropy':0} name={name} stroke={color} strokeWidth={2} dot={false} connectNulls={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer>:<p>No Jev outputs in this window.</p>}</>}
 {view==='api'&&<><div className="lab-table-scroll"><table><caption>API totals cover the current match; agreement counts cover the displayed window.</caption><thead><tr><th>Bot</th><th>Jev calls</th><th>Input tokens</th><th>Output tokens</th><th>Retries</th><th>Search overrides</th><th>N-tuple overrides</th><th>Neither agreed</th><th>All three agreed</th></tr></thead><tbody>{visible.map(b=>{const c=agreementCounts(rows[b.id]??[]);return <tr key={b.id}><th>{botName(b.policy)}</th><td>{b.calls}</td><td>{b.unknown?'Unavailable ('+b.input+' reported)':b.input}</td><td>{b.unknown?'Unavailable ('+b.output+' reported)':b.output}</td><td>{b.apiRetries}</td><td>{c.searchKnown?c.searchOverrides+' / '+c.searchKnown:'Unavailable'}</td><td>{c.learnedKnown?c.learnedOverrides+' / '+c.learnedKnown:'Unavailable'}</td><td>{c.bothKnown?c.neither+' / '+c.bothKnown:'Unavailable'}</td><td>{c.bothKnown?c.both+' / '+c.bothKnown:'Unavailable'}</td></tr>})}</tbody></table></div><p>Overrides mean disagreements only. Cost is unavailable because no official price is configured.</p></>}
 <p className="lab-note">Memory holds 128 detailed moves and 2,000 numeric points per board. Inspect can load older moves from IndexedDB until Restart. A storage error means older history may be incomplete. No new provider requests are made by these charts.</p></div>}</details>;
}
