'use client';
import {useEffect,useRef,useState} from 'react';
import {Play,Pause,RotateCcw,SkipForward,Shuffle,Eye,EyeOff,ArrowUpRight} from 'lucide-react';
import {Turnstile} from '@marsidev/react-turnstile';
import Link from 'next/link';
import {Button} from './ui/button';
import {Tabs,TabsList,TabsTrigger} from './ui/tabs';
import SiteNav from './site-nav';
import Board,{arrows} from './board';
import LabCharts from './lab-charts';
import DecisionInspector from './decision-inspector';
import {MatchController,terminal,type LabBoard} from '@/lib/match-controller';
import {workerDecision} from '@/lib/search';
import {PLAY_BOTS,PLAY_OPPONENTS,WATCH_PRESETS,botName,botColor,statusText,type WatchPreset} from '@/lib/play-options';
import {policyInfo,type PolicyId} from '@/public/policy-catalog';
import type {Direction} from '@/public/engine';
import type {Decision} from '@/lib/types';
const nameOf=(b:LabBoard)=>botName(b.policy);
type Connection={ready:boolean;verified:boolean;protected:boolean;native:boolean;ultraLocal:boolean};
export default function PolicyLab(){const worker=useRef<Worker|null>(null),[,version]=useState(0),[mounted,setMounted]=useState(false),[preset,setPreset]=useState<WatchPreset>('specialists'),[draft,setDraft]=useState('first-light'),[inspect,setInspect]=useState<string|null>(null),[connection,setConnection]=useState<Connection|null>(null);
 const [match]=useState(()=>{const m=new MatchController(()=>{},{search:board=>{if(!worker.current)worker.current=new Worker('/search-worker.js',{type:'module'});return workerDecision(worker.current,board);}});m.configure('play',['blind-dual']);return m;});
 const refresh=()=>version(v=>v+1);async function checkConnection(){try{setConnection(await (await fetch('/api/status')).json());}catch{setConnection({ready:false,verified:false,protected:true,native:false,ultraLocal:false});}}
 useEffect(()=>{match.changed=refresh;setMounted(true);void checkConnection();const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,select,textarea,button,a,[contenteditable=true],[role=tab],dialog'))return;const d=({ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'} as Record<string,Direction>)[e.key];if(d&&match.mode==='play'&&!document.querySelector('dialog[open]')){e.preventDefault();match.human(d);}};document.addEventListener('keydown',key);return ()=>{match.changed=()=>{};match.dispose();worker.current?.terminate();worker.current=null;document.removeEventListener('keydown',key);};},[match]);
 useEffect(()=>setDraft(match.seed),[match.seed]);
 const complete=match.boards.every(terminal),inspected=match.boards.find(b=>b.id===inspect),jevSelected=match.boards.filter(b=>policyInfo(b.policy)?.jev).length,publicLimit=connection?.protected&&jevSelected>1;
 function reset(seed=draft){match.reset(seed);setDraft(seed);setInspect(null);}
 function configure(mode:'play'|'compare',policies?:PolicyId[]){match.configure(mode,policies);setInspect(null);}
 function choosePreset(value:WatchPreset){setPreset(value);if(value!=='custom')configure('compare',[...WATCH_PRESETS[value].bots]);}
 function changeMode(mode:'play'|'compare'){if(mode==='play')configure('play',[PLAY_OPPONENTS.some(b=>b.id===match.opponent)?match.opponent:'blind-dual']);else configure('compare',preset==='custom'?match.selected.filter(id=>PLAY_BOTS.some(b=>b.id===id)):[...WATCH_PRESETS[preset].bots]);}
 function toggle(id:PolicyId){const selected=match.selected.includes(id)?match.selected.filter(p=>p!==id):[...match.selected,id];if(selected.length>=2&&selected.length<=5){setPreset('custom');configure('compare',selected);}}
 function renderBoard(b:LabBoard){const last=b.records[0],info=policyInfo(b.policy);const animation:Decision|null=last&&match.speedFor(b)!=='ultra'?{...last,scoreBefore:b.game.score-last.gain,scoreGain:last.gain}:null;const evidence=last?.evidence as any;return <article className="lab-player" key={b.id} style={{'--policy-color':botColor(b.policy)} as React.CSSProperties} data-policy={b.policy}><div className="lab-player-head"><button className="lab-player-name" onClick={()=>setInspect(b.id)} aria-label={'Inspect '+nameOf(b)}><span>{b.policy==='human'?'Arrow keys or swipe':info?.jev?'Jev 1.13.0':b.policy==='ntuple'?'Pretrained 2048 bot':'Runs locally'}</span><h2>{nameOf(b)}</h2></button><div className="lab-score"><small>Score</small><strong key={b.game.score} className="score-value" data-testid={b.policy+'-score'}>{b.game.score.toLocaleString()}</strong></div></div><div className={'lab-board-wrap '+(match.speedFor(b)==='ultra'?'no-motion':'')}><Board board={b.game.board} last={animation} label={nameOf(b)+' board'} onMove={b.policy==='human'?d=>match.human(d):undefined} over={terminal(b)}/></div><div className="lab-board-state"><span className={'status-pill '+(b.error?'has-error':terminal(b)?'is-finished':b.busy?'is-busy':'')} role="status">{statusText(b.status)}</span><span>Highest <b>{Math.max(...b.game.board).toLocaleString()}</b> · <b data-testid={b.policy+'-moves'}>{b.game.moves}</b> moves</span></div>{b.policy==='human'?<div className="lab-touch-controls" aria-label="Touch move controls">{(['left','up','down','right'] as Direction[]).map(d=><Button variant="outline" size="icon" key={d} aria-label={'Move '+d} onClick={()=>match.human(d)}>{arrows[d]}</Button>)}</div>:<><button className="lab-last-choice" onClick={()=>setInspect(b.id)}><span>{last?<><b>{evidence?.selected_candidate?'Candidate '+evidence.selected_candidate+' → ':''}{arrows[last.direction]} {last.direction}</b><small>{last.ms.toFixed(1)} ms</small></>:'Press Step to see a move'}</span><span>Inspect <ArrowUpRight size={14}/></span></button></>}{b.error&&<div className="lab-error" role="alert"><p>{b.error.replace(/\bpolicy\b/gi,'bot')}</p><Button variant="outline" disabled={b.busy} onClick={()=>match.retry(b.id)}>Retry {nameOf(b)}</Button></div>}</article>;}
 return <div className="study-shell"><SiteNav active="play"/><main className="play-main"><div className="play-intro"><div><h1>Play 2048 against Jev</h1><p>Play yourself or watch different bots take on the same board.</p></div><Link className="text-link" href="/research">Methods and results <ArrowUpRight size={16}/></Link></div>{!mounted?<p role="status">Loading boards…</p>:<><div className="mode-row"><Tabs value={match.mode} onValueChange={v=>changeMode(v as 'play'|'compare')}><TabsList aria-label="Game mode"><TabsTrigger value="play">You vs Jev</TabsTrigger><TabsTrigger value="compare">Watch the bots</TabsTrigger></TabsList></Tabs><span className="connection-badge"><i/>{!connection?'Checking connection':connection.ready&&connection.verified?'Jev API connected':connection.ready?'Verification needed':'Jev unavailable'}</span></div>
 {connection?.protected&&!connection.ready&&<div className="notice">Jev is unavailable on this server. Expectimax runs locally.</div>}{connection?.protected&&!connection.verified&&<div className="verification"><p>Complete the human check to use Jev or N-tuple.</p>{process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY&&<Turnstile siteKey={process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY} options={{action:'arcade'}} onSuccess={async token=>{await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});await checkConnection();}}/>}</div>}
 <section className="lab-setup" aria-label="Choose bots">{match.mode==='play'?<label className="opponent-selector">Choose your opponent <select aria-label="Choose your opponent" value={match.opponent} onChange={e=>configure('play',[e.target.value as PolicyId])}>{PLAY_OPPONENTS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>:<><label className="opponent-selector">Choose bots <select aria-label="Choose bots" value={preset} onChange={e=>choosePreset(e.target.value as WatchPreset)}><option value="inputs">Compare Jev inputs</option><option value="specialists">Compare specialists</option><option value="custom">Custom</option></select></label><div className="policy-selector" aria-label="Select bots to compare"><div className="policy-picker">{PLAY_BOTS.map(p=><label key={p.id} className={match.selected.includes(p.id)?'selected':''}><input type="checkbox" checked={match.selected.includes(p.id)} disabled={match.selected.includes(p.id)?match.selected.length<=2:match.selected.length>=5||!!(connection?.protected&&policyInfo(p.id)?.jev&&jevSelected>=1)} onChange={()=>toggle(p.id)}/><span><b>{p.name}</b><small>{p.description}</small></span></label>)}</div><p>{match.selected.length}/5 selected · Select 2–5 bots. Changing bots restarts the match.</p></div></>}<p className="lab-note">All Jev options use one model. “Both experts” supplies expectimax search results and n-tuple learned values.</p></section>
 {publicLimit&&<p className="notice">This hosted demo runs one Jev board at a time. Choose Custom to change bots. Local runs can use several.</p>}
 <div className="lab-controls"><div className="lab-primary-controls"><Button id="run" disabled={!connection||complete||!!publicLimit} onClick={()=>match.running?match.pause():match.run()}>{match.running?<Pause/>:<Play/>}{match.running?'Pause':'Run'}</Button><Button id="step" variant="outline" disabled={!connection||match.running||complete||!!publicLimit} onClick={()=>void match.step()}><SkipForward/>Step</Button><label className="lab-speed">Speed <select aria-label="Speed" value={match.speed} onChange={e=>match.setSpeed(e.target.value as typeof match.speed)}><option value="step">Step</option><option value="normal">Normal</option><option value="fast">Fast</option><option value="ultra" disabled={!connection?.ultraLocal}>Ultra · local bots only</option></select></label><Button id="restart" variant="ghost" onClick={()=>reset()}><RotateCcw/>Restart</Button></div><div className="lab-seed"><label>Seed <input aria-label="Seed" value={draft} maxLength={60} onChange={e=>setDraft(e.target.value)}/></label><Button variant="ghost" size="sm" onClick={()=>reset()}>Use seed</Button><Button variant="ghost" size="icon" aria-label="Shuffle seed" onClick={()=>reset(crypto.randomUUID().slice(0,8))}><Shuffle size={16}/></Button></div></div>
 {match.mode==='compare'&&<div className="lab-visibility" aria-label="Board visibility">{match.boards.map(b=><button key={b.id} aria-pressed={!b.hidden} onClick={()=>{b.hidden=!b.hidden;refresh();}}>{b.hidden?<EyeOff size={14}/>:<Eye size={14}/>} {nameOf(b)}</button>)}</div>}
 <div className={'lab-arena '+(match.mode==='play'?'play-arena':'compare-arena')} data-count={match.boards.filter(b=>!b.hidden).length}>{match.boards.filter(b=>!b.hidden).map(renderBoard)}</div>{match.boards.every(b=>b.hidden)&&<p className="lab-empty">Hiding a board does not pause it. Use the buttons above to show it.</p>}
 <div className="lab-match-summary"><span>{match.boards.filter(terminal).length}/{match.boards.length} boards finished</span><span>{match.boards.reduce((s,b)=>s+b.calls,0)} Jev calls</span><span>Play continues after reaching 2048.</span></div>
 {complete&&<section className="lab-finish"><h2>Game over</h2><p>Score winner: {match.results().filter(r=>r.score===Math.max(...match.results().map(r=>r.score))).map(r=>botName(r.policy)).join(' & ')}. Reached 2048: {match.results().filter(r=>r.reached).map(r=>botName(r.policy)).join(', ')||'none'}.</p></section>}
 <LabCharts boards={match.boards}/><section className="play-method"><h2>Seeds and speed</h2><p>The same seed repeats the starting board and random stream. Different moves change the empty cells, so later tile positions can differ.</p><p>Ultra runs 100 moves per batch for local Expectimax and N-tuple. It does not speed up Jev. A hosted N-tuple model may need time to wake before its first move. Its verified tile limit is 32,768; an unsupported board produces an error, not a substitute move.</p><Link className="text-link" href="/research">Methods and results <ArrowUpRight size={16}/></Link></section></>}
 </main><footer className="study-footer"><span>2048</span><Link href="/research#attribution">Source code and licenses</Link></footer>{inspected&&<DecisionInspector key={inspected.id} board={inspected} onClose={()=>setInspect(null)}/>}</div>;
}
