'use client';
import {useEffect,useRef,useState} from 'react';
import {Play,Pause,RotateCcw,SkipForward,Shuffle,Eye,EyeOff,ArrowUpRight} from 'lucide-react';
import {Turnstile} from '@marsidev/react-turnstile';
import Link from 'next/link';
import {Button} from './ui/button';
import {Tabs,TabsList,TabsTrigger} from './ui/tabs';
import SiteNav from './site-nav';
import Board,{ScoreGain,arrows} from './board';
import LabCharts from './lab-charts';
import DecisionInspector from './decision-inspector';
import {DecisionPanel,MatchTelemetry,RivalDock,STACK,Countdown,MatchResult,ExperimentLog,appendLog,readLog,entryFrom,type LogEntry} from './experiment-ui';
import {motion,useReducedMotion} from 'motion/react';
import {MatchController,terminal,type LabBoard} from '@/lib/match-controller';
import {workerDecision} from '@/lib/search';
import {PLAY_BOTS,PLAY_OPPONENTS,WATCH_PRESETS,botName,botColor,statusText,type WatchPreset} from '@/lib/play-options';
import {policyInfo,type PolicyId} from '@/public/policy-catalog';
import type {Direction} from '@/public/engine';
import type {Decision} from '@/lib/types';
const nameOf=(b:LabBoard)=>botName(b.policy);
type Connection={ready:boolean;verified:boolean;protected:boolean;native:boolean;ultraLocal:boolean};
export default function PolicyLab(){const worker=useRef<Worker|null>(null),[,version]=useState(0),[mounted,setMounted]=useState(false),[preset,setPreset]=useState<WatchPreset>('specialists'),[draft,setDraft]=useState('first-light'),[inspect,setInspect]=useState<string|null>(null),[connection,setConnection]=useState<Connection|null>(null),[countdown,setCountdown]=useState<number|null>(null),[log,setLog]=useState<LogEntry[]>([]),countdownTimer=useRef<ReturnType<typeof setTimeout>|null>(null),logged=useRef(-1),reduce=useReducedMotion();
 const [match]=useState(()=>{const m=new MatchController(()=>{},{search:board=>{if(!worker.current)worker.current=new Worker('/search-worker.js',{type:'module'});return workerDecision(worker.current,board);}});m.configure('play',['blind-dual']);return m;});
 const refresh=()=>version(v=>v+1);async function checkConnection(){try{setConnection(await (await fetch('/api/status')).json());}catch{setConnection({ready:false,verified:false,protected:true,native:false,ultraLocal:false});}}
 useEffect(()=>{match.changed=refresh;setMounted(true);void checkConnection();const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,select,textarea,button,a,[contenteditable=true],[role=tab],dialog'))return;const d=({ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'} as Record<string,Direction>)[e.key];if(d&&match.mode==='play'&&!document.querySelector('dialog[open]')){e.preventDefault();match.human(d);}};document.addEventListener('keydown',key);return ()=>{match.changed=()=>{};match.dispose();worker.current?.terminate();worker.current=null;document.removeEventListener('keydown',key);};},[match]);
 useEffect(()=>setDraft(match.seed),[match.seed]);
 useEffect(()=>{setLog(readLog());return ()=>{if(countdownTimer.current)clearTimeout(countdownTimer.current);};},[]);
 const complete=match.boards.every(terminal),inspected=match.boards.find(b=>b.id===inspect),jevSelected=match.boards.filter(b=>policyInfo(b.policy)?.jev).length,publicLimit=connection?.protected&&jevSelected>2;
 useEffect(()=>{if(mounted&&complete&&logged.current!==match.generation){logged.current=match.generation;setLog(appendLog(entryFrom(match.boards,match.seed,match.mode)));}});
 function cancelCountdown(){if(countdownTimer.current)clearTimeout(countdownTimer.current);countdownTimer.current=null;setCountdown(null);}
 // A fresh You vs Jev match starts with a short 3-2-1 so the race has a clear start.
 function start(){if(match.running){cancelCountdown();match.pause();return;}if(countdown!==null){cancelCountdown();return;}
  if(match.mode!=='play'||reduce||match.boards.some(b=>b.game.moves>0)){match.run();return;}
  const tick=(n:number)=>{setCountdown(n);countdownTimer.current=setTimeout(()=>{if(n>1)tick(n-1);else{setCountdown(0);countdownTimer.current=setTimeout(()=>{setCountdown(null);countdownTimer.current=null;},450);match.run();}},700);};tick(3);}
 function reset(seed=draft){cancelCountdown();match.reset(seed);setDraft(seed);setInspect(null);}
 function configure(mode:'play'|'compare',policies?:PolicyId[]){cancelCountdown();match.configure(mode,policies);setInspect(null);}
 function choosePreset(value:WatchPreset){setPreset(value);if(value!=='custom')configure('compare',[...WATCH_PRESETS[value].bots]);}
 function changeMode(mode:'play'|'compare'){if(mode==='play')configure('play',[PLAY_OPPONENTS.some(b=>b.id===match.opponent)?match.opponent:'blind-dual']);else configure('compare',preset==='custom'?match.selected.filter(id=>PLAY_BOTS.some(b=>b.id===id)):[...WATCH_PRESETS[preset].bots]);}
 function toggle(id:PolicyId){const selected=match.selected.includes(id)?match.selected.filter(p=>p!==id):[...match.selected,id];if(selected.length>=2&&selected.length<=5){setPreset('custom');configure('compare',selected);}}
 function renderBoard(b:LabBoard){const last=b.records[0],info=policyInfo(b.policy);const animation:Decision|null=last&&match.speedFor(b)!=='ultra'?{...last,scoreBefore:b.game.score-last.gain,scoreGain:last.gain}:null;const evidence=last?.evidence as any;return <article className="lab-player" key={b.id} style={{'--policy-color':botColor(b.policy)} as React.CSSProperties} data-policy={b.policy}><div className="lab-player-head"><button className="lab-player-name" onClick={()=>setInspect(b.id)} aria-label={'Inspect '+nameOf(b)}><span>{b.policy==='human'?'Arrow keys or swipe':info?.jev?'Jev 1.13.0':b.policy==='ntuple'?'Pretrained 2048 bot':'Runs locally'}</span><h2>{nameOf(b)}</h2></button><div className="lab-score"><ScoreGain gain={animation?.scoreGain??0} id={animation?.id}/><small>Score</small><strong key={b.game.score} className="score-value" data-testid={b.policy+'-score'}>{b.game.score.toLocaleString()}</strong></div></div><div className={'lab-board-wrap '+(match.speedFor(b)==='ultra'?'no-motion':'')}><Board board={b.game.board} last={animation} label={nameOf(b)+' board'} onMove={b.policy==='human'?d=>match.human(d):undefined} over={terminal(b)}/></div><div className="lab-board-state"><span className={'status-pill '+(b.error?'has-error':terminal(b)?'is-finished':b.busy?'is-busy':'')} role="status">{statusText(b.status)}</span><span>Highest <b>{Math.max(...b.game.board).toLocaleString()}</b> · <b data-testid={b.policy+'-moves'}>{b.game.moves}</b> moves</span></div>{b.policy==='human'?<div className="lab-touch-controls" aria-label="Touch move controls"><span className="mono-label key-hint">Arrow keys · swipe · drag</span>{(['left','up','down','right'] as Direction[]).map(d=><Button variant="outline" size="icon" key={d} aria-label={'Move '+d} onClick={()=>match.human(d)}>{arrows[d]}</Button>)}</div>:<DecisionPanel board={b} onInspect={()=>setInspect(b.id)}/>}{b.error&&<div className="lab-error" role="alert"><p>{b.error.replace(/\bpolicy\b/gi,'bot')}</p><Button variant="outline" disabled={b.busy} onClick={()=>match.retry(b.id)}>Retry {nameOf(b)}</Button></div>}</article>;}
 return <div className="study-shell"><SiteNav active="play"/><main className="play-main"><div className="play-intro"><div><h1>Play 2048 against Jev</h1><p>Play yourself or watch different bots take on the same seeded board.</p><ul className="stack-chips" aria-label="How it is built">{STACK.map(t=><li key={t}><Link href="/research">{t}</Link></li>)}</ul></div><Link className="text-link" href="/research">Methods and results <ArrowUpRight size={16}/></Link></div>{!mounted?<p role="status">Loading boards…</p>:<><div className="mode-row"><Tabs value={match.mode} onValueChange={v=>changeMode(v as 'play'|'compare')}><TabsList aria-label="Game mode">{(['play','compare'] as const).map(v=><TabsTrigger key={v} value={v}>{match.mode===v&&<motion.span layoutId="mode-pill" className="tab-pill" transition={{type:'spring',stiffness:520,damping:40}}/>}<span className="tab-label">{v==='play'?'You vs Jev':'Watch the bots'}</span></TabsTrigger>)}</TabsList></Tabs><span className="connection-badge"><i/>{!connection?'Checking connection':connection.ready&&connection.verified?'Jev API connected':connection.ready?'Verification needed':'Jev unavailable'}</span></div>
 {connection?.protected&&!connection.ready&&<div className="notice">Jev is unavailable on this server. Expectimax runs locally.</div>}{connection?.protected&&!connection.verified&&<div className="verification"><p>Complete the human check to use Jev or N-tuple.</p>{process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY&&<Turnstile siteKey={process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY} options={{action:'arcade'}} onSuccess={async token=>{await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});await checkConnection();}}/>}</div>}
 <div className="experiment-panel" data-mode={match.mode}><div className="experiment-panel-head"><span className="mono-label">Experiment setup</span><span className="mono-label experiment-readout">seed <b>{match.seed}</b> · speed <b>{match.speed}</b> · {match.boards.length} boards</span></div><section className="lab-setup" aria-label="Choose bots">{match.mode==='play'?<label className="opponent-selector">Choose your opponent <select aria-label="Choose your opponent" value={match.opponent} onChange={e=>configure('play',[e.target.value as PolicyId])}>{PLAY_OPPONENTS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>:<><label className="opponent-selector">Choose bots <select aria-label="Choose bots" value={preset} onChange={e=>choosePreset(e.target.value as WatchPreset)}><option value="inputs">Compare Jev inputs</option><option value="specialists">Compare specialists</option><option value="custom">Custom</option></select></label><div className="policy-selector" aria-label="Select bots to compare"><div className="policy-picker">{PLAY_BOTS.map(p=><label key={p.id} className={match.selected.includes(p.id)?'selected':''}><input type="checkbox" checked={match.selected.includes(p.id)} disabled={match.selected.includes(p.id)?match.selected.length<=2:match.selected.length>=5||!!(connection?.protected&&policyInfo(p.id)?.jev&&jevSelected>=2)} onChange={()=>toggle(p.id)}/><span><b>{p.name}</b><small>{p.description}</small></span></label>)}</div><p>{match.selected.length}/5 selected · Select 2–5 bots. Changing bots restarts the match.</p></div></>}<p className="lab-note">All Jev options use one model. “Both experts” supplies expectimax search results and n-tuple learned values.</p></section>
 
 <div className="lab-controls"><div className="lab-primary-controls"><Button id="run" disabled={!connection||complete||!!publicLimit} onClick={start}>{match.running||countdown!==null?<Pause/>:<Play/>}{match.running?'Pause':countdown!==null?'Cancel':match.mode==='play'&&match.boards.every(b=>b.game.moves===0)?'Start match':'Run'}</Button><Button id="step" variant="outline" disabled={!connection||match.running||complete||!!publicLimit} onClick={()=>void match.step()}><SkipForward/>Step</Button><label className="lab-speed">Speed <select aria-label="Speed" value={match.speed} onChange={e=>match.setSpeed(e.target.value as typeof match.speed)}><option value="step">Step</option><option value="normal">Normal</option><option value="fast">Fast</option><option value="ultra" disabled={!connection?.ultraLocal}>Ultra · local bots only</option></select></label><Button id="restart" variant="ghost" onClick={()=>reset()}><RotateCcw/>Restart</Button></div><div className="lab-seed"><label>Seed <input aria-label="Seed" value={draft} maxLength={60} onChange={e=>setDraft(e.target.value)}/></label><Button variant="ghost" size="sm" onClick={()=>reset()}>Use seed</Button><Button variant="ghost" size="icon" aria-label="Shuffle seed" onClick={()=>reset(crypto.randomUUID().slice(0,8))}><Shuffle size={16}/></Button></div></div></div>
 {publicLimit&&<p className="notice">This hosted demo runs up to two Jev boards at a time. Choose Custom to change bots. Local runs can use several.</p>}
 {match.mode==='compare'&&<div className="lab-visibility" aria-label="Board visibility">{match.boards.map(b=><button key={b.id} aria-pressed={!b.hidden} onClick={()=>{b.hidden=!b.hidden;refresh();}}>{b.hidden?<EyeOff size={14}/>:<Eye size={14}/>} {nameOf(b)}</button>)}</div>}
 <div className="play-stage"><Countdown value={countdown}/>{match.mode==='play'&&match.boards.find(b=>b.policy!=='human')&&<RivalDock board={match.boards.find(b=>b.policy!=='human')!}/>}<div className={'lab-arena '+(match.mode==='play'?'play-arena':'compare-arena')} data-count={match.boards.filter(b=>!b.hidden).length}>{match.boards.filter(b=>!b.hidden).map(renderBoard)}</div></div>{match.boards.every(b=>b.hidden)&&<p className="lab-empty">Hiding a board does not pause it. Use the buttons above to show it.</p>}
 <MatchTelemetry boards={match.boards} mode={match.mode}/>
 {complete&&<MatchResult boards={match.boards} mode={match.mode} seed={match.seed} onReplay={()=>reset(match.seed)} onNewSeed={()=>reset(crypto.randomUUID().slice(0,8))}/>}
 <LabCharts boards={match.boards}/><ExperimentLog entries={log} onClear={()=>{try{localStorage.removeItem('jev-experiment-log');}catch{}setLog([]);}}/><section className="play-method"><h2>Seeds and speed</h2><p>The same seed repeats the starting board and random stream. Different moves change the empty cells, so later tile positions can differ.</p><p>Ultra runs 100 moves per batch for local Expectimax and N-tuple. It does not speed up Jev. A hosted N-tuple model may need time to wake before its first move. Its verified tile limit is 32,768; an unsupported board produces an error, not a substitute move.</p><Link className="text-link" href="/research">Methods and results <ArrowUpRight size={16}/></Link></section></>}
 </main><footer className="study-footer"><span>Jev 2048 · <a href="https://armanhassan.com">More of my work</a></span><Link href="/research#attribution">Source code and licenses</Link></footer>{inspected&&<DecisionInspector key={inspected.id} board={inspected} onClose={()=>setInspect(null)}/>}</div>;
}
