import {numeric,schemas,POINT_LIMIT,type NumericTurn,agreementCounts} from './turn-analytics';
import type {LabDecision} from './match-controller';
let opening:Promise<IDBDatabase>|undefined;
const active=new Set<string>();let initialized=false;
function remember(){try{sessionStorage.setItem('jev-history-boards',JSON.stringify([...active]));}catch{}}
export function registerHistory(id:string){if(!initialized&&typeof sessionStorage!=='undefined'){initialized=true;try{const previous=JSON.parse(sessionStorage.getItem('jev-history-boards')||'[]');for(const old of previous)if(typeof old==='string')void dropHistory(old).catch(()=>{});}catch{}}active.add(id);remember();}
function database(){if(typeof indexedDB==='undefined')return Promise.reject(Error('Local history storage is unavailable. Only recent moves remain in memory.'));return opening??=new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('jev-turn-history',1);r.onupgradeneeded=()=>{r.result.createObjectStore('moves',{keyPath:['board','move']});r.result.createObjectStore('points',{keyPath:['board','move']});r.result.createObjectStore('schemas',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>{opening=undefined;reject(Error('Local history storage is unavailable. Only recent moves remain in memory.'));};});}
function done(tx:IDBTransaction){return new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(Error('Local history storage is full or unavailable. Older moves may be missing.'));tx.onabort=()=>reject(Error('Local history storage write failed.'));});}
export async function saveHistory(board:string,record:LabDecision){if(typeof indexedDB==='undefined')return;const db=await database();if(!active.has(board)||!record.analytics)return;const tx=db.transaction(['moves','points','schemas'],'readwrite'),e=record.evidence as any;let packed=record;if(e?.request_schema_id){const schema=schemas.get(e.request_schema_id);if(schema)tx.objectStore('schemas').put({id:e.request_schema_id,value:schema});const {questions,...request}=e.exact_request;packed={...record,evidence:{...e,exact_request:request}};}
 tx.objectStore('moves').put({board,move:record.move,record:packed});tx.objectStore('points').put({board,move:record.move,row:numeric(record.analytics)});await done(tx);
}
export async function dropHistory(board:string){active.delete(board);remember();if(typeof indexedDB==='undefined')return;const db=await database();const tx=db.transaction(['moves','points'],'readwrite');for(const store of ['moves','points'])tx.objectStore(store).delete(IDBKeyRange.bound([board,0],[board,Infinity]));await done(tx);}
function get<T>(db:IDBDatabase,store:string,key:IDBValidKey){return new Promise<T|undefined>((resolve,reject)=>{const r=db.transaction(store).objectStore(store).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('Stored history could not be read.'));});}
export async function historicalMove(board:string,move:number){const db=await database(),saved=await get<{record:LabDecision}>(db,'moves',[board,move]);if(!saved)return null;const r=saved.record,e=r.evidence as any;if(e?.request_schema_id){const schema=await get<{value:any}>(db,'schemas',e.request_schema_id);if(schema)e.exact_request={...schema.value,state:e.exact_request.state};}return r;}
export type ChartRow=NumericTurn&{cumulative:ReturnType<typeof agreementCounts>};
export async function historicalWindow(board:string,start:number,end:number):Promise<ChartRow[]>{const db=await database(),from=Math.max(start,end-POINT_LIMIT+1),rows:ChartRow[]=[],counts=agreementCounts([]);return new Promise((resolve,reject)=>{const request=db.transaction('points').objectStore('points').openCursor(IDBKeyRange.bound([board,from],[board,end]));request.onerror=()=>reject(Error('Stored chart history could not be read.'));request.onsuccess=()=>{const cursor=request.result;if(!cursor){resolve(rows);return;}const row=cursor.value.row as NumericTurn,delta=agreementCounts([row]);for(const k of Object.keys(counts) as (keyof typeof counts)[])counts[k]+=delta[k];if(row.move>=from)rows.push({...row,cumulative:{...counts}});cursor.continue();};});}
export function currentWindow(rows:NumericTurn[]):ChartRow[]{const counts=agreementCounts([]);return rows.map(row=>{const d=agreementCounts([row]);for(const k of Object.keys(counts) as (keyof typeof counts)[])counts[k]+=d[k];return {...row,cumulative:{...counts}};});}
export async function findHistoricalEvent(board:string,kind:string){const db=await database();return new Promise<number|null>((resolve,reject)=>{const request=db.transaction('points').objectStore('points').openCursor(IDBKeyRange.bound([board,0],[board,Infinity]),'prev');request.onerror=()=>reject(Error('History unavailable'));request.onsuccess=()=>{const cursor=request.result;if(!cursor){resolve(null);return;}const r=cursor.value.row as NumericTurn;if(kind==='score'?r.scoreIncrease>=128:kind==='confidence'?r.margin!==null&&r.margin<.1:kind==='override'?r.overridesSearch||r.overridesLearned:kind==='end'?r.gameOver:!!r.errorCategory||r.retries>0){resolve(r.move);return;}cursor.continue();};});}
