import {makeAnalytics,compactEvidence,numeric,trimRetained,updateAudit,DETAIL_LIMIT,POINT_LIMIT,type TurnAnalytics,type NumericTurn,type TurnMeta} from './turn-analytics';
import {registerHistory,saveHistory,dropHistory} from './analytics-history';
import {requestLocalBatch,validateBatch,type BatchInput} from './local-batch';
import {ntupleDecision} from './ntuple-client';
import {newGame,move,slide,gameOver,legalMoves,heuristic,type Game,type Direction} from '@/public/engine';
import {POLICY_LIST,policyInfo,type PolicyId} from '@/public/policy-catalog';
import {reliableDecision,PausedDecision,type WireDecision} from './reliability';
import type {SearchDecision} from '@/public/search-solver';
export type Status='ready'|'running'|'waiting for Jev'|'retrying'|'paused'|'API failure'|'reached 2048'|'game over'|'waiting for N-tuple'|'policy failure'|'service waking'|'model loading'|'timeout'|'rate limited'|'unavailable'|'quota reached';
export type Point={move:number;score:number;highest:number;empty:number;ms:number|null;analytics?:NumericTurn};
export type LabDecision={id:string;move:number;before:number[];after:number[];preSpawn:number[];direction:Direction;gain:number;spawn:{index:number;value:number};probabilities:Record<string,number>|null;model?:string;policy:string;ms:number;usage:WireDecision['usage'];evidence?:unknown;analytics?:TurnAnalytics;analyticsMeta?:TurnMeta};
export type LabBoard={id:string;policy:PolicyId|'human';game:Game;status:Status;busy:boolean;hidden:boolean;error:string;archiveError?:string;analyticsRevision:number;apiRetries:number;animationDelay:number;failures:{move:number;timestamp:string;category:string;attempts:number;retries:number}[];records:LabDecision[];points:Point[];calls:number;input:number;output:number;unknown:number;totalMs:number;decisions:number;timer:ReturnType<typeof setTimeout>|null;batchStats?:{moves:number;elapsedMs:number;computeMs:number;requestMs:number}};
export type Result={seed:string;policy:string;score:number;highest:number;moves:number;reached:boolean;calls:number;input:number;output:number;unknown:number;averageMs:number|null};
export const terminal=(b:LabBoard)=>gameOver(b.game.board);
const point=(g:Game,ms:number|null):Point=>({move:g.moves,score:g.score,highest:Math.max(...g.board),empty:g.board.filter(v=>!v).length,ms});
export class MatchController{
 private auditsPending=0;
 private batchAborts=new Map<string,AbortController>();private batchSequence=0;private jevSpeed:'step'|'normal'|'fast'='normal';private instanceId=crypto.randomUUID();private flights=new Map<string,Promise<void>>();
 boards:LabBoard[]=[];seed='first-light';mode:'play'|'compare'='play';opponent:PolicyId='assisted';selected:PolicyId[]=['blind-board','blind-dual','search'];speed:'step'|'normal'|'fast'|'ultra'='normal';running=false;generation=0;pauseVersion=0;batch:{target:number;index:number;base:string;results:Result[]}|null=null;completedBatches:Result[]=[];
 constructor(public changed:()=>void,public dependencies:{jev?:typeof reliableDecision;ntuple?:typeof ntupleDecision;localBatch?:typeof requestLocalBatch;search:(board:number[])=>Promise<SearchDecision>}){this.reset();}
 reset(seed=this.seed,keepBatch=false){this.pause();this.generation++;this.seed=seed;if(!keepBatch){this.batch=null;}const policies=this.mode==='play'?['human',this.opponent] as const:this.selected;for(const b of this.boards)void dropHistory(b.id).catch(()=>{});this.boards=policies.map(policy=>{const game=newGame(seed),id=crypto.randomUUID();registerHistory(id);return {id,analyticsRevision:0,apiRetries:0,animationDelay:0,failures:[],policy,game,status:'ready',busy:false,hidden:false,error:'',records:[],points:[point(game,null)],calls:0,input:0,output:0,unknown:0,totalMs:0,decisions:0,timer:null};});this.changed();}
 configure(mode:this['mode'],policies?:PolicyId[]){this.mode=mode;if(policies){if(mode==='play')this.opponent=policies[0];else this.selected=POLICY_LIST.filter(p=>policies.includes(p.id)).map(p=>p.id).slice(0,5);}this.reset();}
 pause(){for(const abort of this.batchAborts.values())abort.abort();this.running=false;this.pauseVersion++;for(const b of this.boards){if(b.timer)clearTimeout(b.timer);b.timer=null;b.animationDelay=0;if(!terminal(b)&&!b.busy&&!b.error)b.status='paused';}this.changed();}
 run(){this.running=true;for(const b of this.boards)void this.tick(b);this.changed();}
 async step(){if(this.running)return;await Promise.all(this.boards.map(b=>this.tick(b)));}
 status(b:LabBoard){b.status=gameOver(b.game.board)?'game over':this.running?'running':'paused';}
 apply(b:LabBoard,direction:Direction,meta:Partial<LabDecision>={},notify=true){if(terminal(b)||!legalMoves(b.game.board).includes(direction))return;const before=b.game.board.slice(),calculated=slide(before,direction);move(b.game,direction);const index=b.game.board.findIndex((v,i)=>v!==calculated.board[i]),ms=meta.ms??0;const record:LabDecision={id:crypto.randomUUID(),move:b.game.moves,before,after:b.game.board.slice(),preSpawn:calculated.board,direction,gain:calculated.score,spawn:{index,value:b.game.board[index]},probabilities:null,policy:b.policy,ms,usage:null,...meta};record.evidence=compactEvidence(record.evidence);record.analytics=makeAnalytics(record,this.seed,b.game.score,meta.analyticsMeta);delete record.analyticsMeta;b.records.unshift(record);b.points.push({...point(b.game,b.policy==='human'?null:ms),analytics:numeric(record.analytics)});trimRetained(b.records,b.points);b.analyticsRevision++;b.apiRetries+=record.analytics.retries;this.saveTurn(b,record);if(b.policy!=='human'){b.totalMs+=ms;b.decisions++;}this.status(b);if(notify){this.changed();this.checkComplete();}}
 private saveTurn(b:LabBoard,r:LabDecision){void saveHistory(b.id,r).catch(()=>{if(this.boards.includes(b)){b.archiveError='Local history storage is unavailable or full. Only recent moves are retained.';this.changed();}});}
 private auditLater(b:LabBoard,record:LabDecision,generation:number){
  const evidence=record.evidence as any;if(evidence?.audit_not_sent?.status!=='pending')return;if(this.auditsPending>=3){evidence.audit_not_sent.status='unavailable';this.saveTurn(b,record);return;}this.auditsPending++;const auditStart=performance.now();
  // A browser worker computes this after the move. Never delay or change gameplay.
  void this.dependencies.search(record.before.slice()).then(result=>{
   if(generation!==this.generation||!this.boards.includes(b))return;
   Object.assign(evidence.audit_not_sent,{status:'complete',expectimax_preferred:result.direction,agrees_expectimax:record.direction===result.direction});if(record.analytics){updateAudit(record.analytics,result.direction,performance.now()-auditStart);const point=b.points.find(p=>p.move===record.move);if(point)point.analytics=numeric(record.analytics);}b.analyticsRevision++;this.saveTurn(b,record);this.changed();
  }).catch(()=>{if(generation===this.generation&&this.boards.includes(b)){evidence.audit_not_sent.status='unavailable';this.saveTurn(b,record);this.changed();}}).finally(()=>{this.auditsPending--;});
 }
 human(direction:Direction){if(this.mode==='play')this.apply(this.boards[0],direction);}
 async tick(b:LabBoard,manualRetry=false){if((this.running&&(b.policy==='assisted'||b.policy.startsWith('blind-')||b.policy==='ntuple'||b.policy==='search')&&this.speedFor(b)==='step')||b.policy==='human'||b.busy||terminal(b)||(b.error&&!manualRetry)||!this.boards.includes(b))return;if(manualRetry)b.error='';b.busy=true;const uiDelay=b.animationDelay;b.animationDelay=0;const generation=this.generation,pause=this.pauseVersion,current=()=>generation===this.generation&&this.boards.includes(b);b.status=policyInfo(b.policy)?.jev?'waiting for Jev':b.policy==='ntuple'?'waiting for N-tuple':'running';this.changed();let releaseSlot:(()=>void)|undefined,slot:Promise<void>|undefined,batchAbort:AbortController|undefined;
 try{const previous=this.flights.get(b.policy);if(previous)await previous;if(!current()||pause!==this.pauseVersion)return;slot=new Promise<void>(resolve=>{releaseSlot=resolve;});this.flights.set(b.policy,slot);if(this.running&&this.speed==='ultra'&&(b.policy==='search'||b.policy==='ntuple')){batchAbort=new AbortController();this.batchAborts.set(b.id,batchAbort);const input:BatchInput={policy:b.policy,seed:this.seed,board:b.game.board.slice(),score:b.game.score,moves:b.game.moves,session:this.instanceId,generation,sequence:++this.batchSequence};const start=performance.now();const result=await (this.dependencies.localBatch??requestLocalBatch)(input,batchAbort.signal);if(current()&&pause===this.pauseVersion&&!batchAbort.signal.aborted){validateBatch(input,result);for(const r of result.records)this.apply(b,r.direction,{ms:r.ms,model:r.model,evidence:r.evidence,analyticsMeta:{ultra:true,uiDelay:0}},false);b.batchStats={moves:result.records.length,elapsedMs:result.elapsedMs,computeMs:result.computeMs,requestMs:performance.now()-start};this.changed();}}
 else if(policyInfo(b.policy)?.jev){const start=performance.now();const result=await (this.dependencies.jev??reliableDecision)({board:b.game.board.slice(),score:b.game.score,moves:b.game.moves,match:this.instanceId+'-'+b.policy,policy:b.policy},{canStart:()=>current()&&pause===this.pauseVersion,onStatus:s=>{if(current()){b.status=s as Status;this.changed();}},onAttempt:r=>{if(current()){if(r.attempted!==false){b.calls++;if(r.usage){b.input+=r.usage.input_tokens;b.output+=r.usage.output_tokens;}else b.unknown++;}this.changed();}}});if(current()&&pause===this.pauseVersion)this.apply(b,result.direction,{probabilities:result.probabilities,model:result.model,ms:performance.now()-start,usage:result.usage,evidence:result.evidence,analyticsMeta:{...result.telemetry,timing:result.timing,totalMs:performance.now()-start,uiDelay}});if(current()&&pause===this.pauseVersion&&b.records[0])this.auditLater(b,b.records[0],generation);}
 else if(b.policy==='ntuple'){const start=performance.now();const result=await (this.dependencies.ntuple??ntupleDecision)(b.game.board.slice(),{match:this.instanceId+'-'+b.policy,generation,sequence:b.game.moves});if(current()&&pause===this.pauseVersion)this.apply(b,result.direction,{ms:result.ms,model:result.model,evidence:result.evidence,analyticsMeta:{totalMs:performance.now()-start,uiDelay}});}
 else{const start=performance.now();const result=b.policy==='search'?await this.dependencies.search(b.game.board.slice()):{direction:heuristic(b.game.board),ms:performance.now()-start};if(current()&&result.direction){if(!legalMoves(b.game.board).includes(result.direction))throw Error('The local policy returned an invalid direction.');this.apply(b,result.direction,{ms:result.ms,evidence:b.policy==='search'?result:undefined,analyticsMeta:{totalMs:performance.now()-start,uiDelay}});}}
 }catch(error){if(current()){if(error instanceof PausedDecision||batchAbort?.signal.aborted)b.status='paused';else{b.error=error instanceof Error?error.message:'Decision failed. Retry this board.';const code=(error as {code?:string}).code,meta=(error as {telemetry?:TurnMeta}).telemetry;b.apiRetries+=meta?.retries??0;b.failures.unshift({move:b.game.moves+1,timestamp:new Date().toISOString(),category:code&&['timeout','rate_limit','rate_limited','illegal_choice','invalid_probabilities','quota_exhausted','unavailable','loading'].includes(code)?code:'request_error',attempts:meta?.attempts??0,retries:meta?.retries??0});b.failures.length=Math.min(b.failures.length,100);b.status=code==='quota_exhausted'?'quota reached':code==='loading'?'model loading':code==='timeout'?'timeout':code==='rate_limit'||code==='rate_limited'?'rate limited':code==='unavailable'?'unavailable':(b.policy==='ntuple'||b.policy==='search')?'policy failure':'API failure';}}}
 finally{if(batchAbort&&this.batchAborts.get(b.id)===batchAbort)this.batchAborts.delete(b.id);if(slot&&this.flights.get(b.policy)===slot)this.flights.delete(b.policy);releaseSlot?.();b.busy=false;if(current()){if(!b.error)this.status(b);this.changed();if(this.running&&!b.error&&!terminal(b)){const delay=this.speedFor(b)==='ultra'?0:this.speedFor(b)==='fast'?(b.policy==='search'||b.policy==='ntuple'?140:0):500;b.animationDelay=delay;b.timer=setTimeout(()=>void this.tick(b),delay);}this.checkComplete();}}
 }
 retry(id:string){const b=this.boards.find(b=>b.id===id);if(b)void this.tick(b,true);}
 speedFor(b:LabBoard){return (b.policy==='assisted'||b.policy.startsWith('blind-'))?(this.speed==='ultra'?this.jevSpeed:this.speed):(b.policy==='search'||b.policy==='ntuple')?this.speed:'normal';}
 setSpeed(speed:this['speed']){if(speed!=='ultra')this.jevSpeed=speed;this.speed=speed;for(const abort of this.batchAborts.values())abort.abort();for(const b of this.boards.filter(b=>b.policy==='assisted'||b.policy.startsWith('blind-')||b.policy==='ntuple'||b.policy==='search')){if(b.timer){clearTimeout(b.timer);b.timer=null;b.animationDelay=0;}if(this.running&&!b.busy&&this.speedFor(b)!=='step')void this.tick(b);}this.changed();}
 results():Result[]{return this.boards.map(b=>({seed:this.seed,policy:b.policy,score:b.game.score,highest:Math.max(...b.game.board),moves:b.game.moves,reached:Math.max(...b.game.board)>=2048,calls:b.calls,input:b.input,output:b.output,unknown:b.unknown,averageMs:b.decisions?b.totalMs/b.decisions:null}));}
 checkComplete(){if(!this.boards.length||!this.boards.every(terminal)||this.boards.some(b=>b.busy))return;if(this.batch){this.batch.results.push(...this.results());this.completedBatches=this.batch.results.slice();if(this.batch.index<this.batch.target){const batch=this.batch,wasRunning=this.running;batch.index++;this.reset(batch.base+'/batch/'+batch.index,true);if(wasRunning)this.run();return;}}this.running=false;this.changed();}
 startBatch(games:number){this.mode='compare';this.speed='fast';this.batch={target:Math.min(10,Math.max(2,games)),index:1,base:this.seed,results:[]};this.completedBatches=[];this.reset(this.batch.base+'/batch/1',true);this.run();}
 dispose(){this.pause();this.generation++;}
}
export function aggregate(results:Result[]){return [...new Set(results.map(r=>r.policy))].map(policy=>{const games=results.filter(r=>r.policy===policy),scores=games.map(r=>r.score).sort((a,b)=>a-b),mean=scores.reduce((a,b)=>a+b,0)/scores.length;return {policy,n:games.length,mean,median:(scores[Math.floor((scores.length-1)/2)]+scores[Math.ceil((scores.length-1)/2)])/2,sd:games.length>1?Math.sqrt(scores.reduce((s,v)=>s+(v-mean)**2,0)/(games.length-1)):0,min:scores[0],max:scores.at(-1),reached:games.filter(g=>g.reached).length,calls:games.reduce((s,g)=>s+g.calls,0),input:games.reduce((s,g)=>s+g.input,0)};});}
