import {nativeDecision,type NtupleDecision} from './ntuple-server';
import {legalMoves,slide,type Direction} from '@/public/engine';
export const CHECKPOINT='41292737878c8663f5928acf7e44d03036635db9f74db62de950c1e4dc7e141d';
export class ModelError extends Error{constructor(public code:string,message:string,public status=503){super(message);}}
export function nativeAvailable(){return !!process.env.NTUPLE_SERVICE_URL||(process.platform==='win32'&&process.env.VERCEL!=='1');}
export function validNativeBoard(board:unknown):board is number[]{return Array.isArray(board)&&board.length===16&&board.every(v=>Number.isSafeInteger(v)&&(v===0||(v>=2&&v<=32768&&Number.isInteger(Math.log2(v)))))&&board.filter(Boolean).length>=2&&!legalMoves(board).some(d=>slide(board,d).board.some(v=>v>32768));}
export function validateNativeResponse(board:number[],r:any){const legal=legalMoves(board);if(!legal.includes(r.direction)||!Number.isFinite(r.compute_ms)||r.compute_ms<0||r.checkpoint!==CHECKPOINT||!Array.isArray(r.options)||r.options.length!==legal.length||new Set(r.options.map((o:any)=>o.direction)).size!==legal.length)throw new ModelError('invalid_response','The model returned an invalid response.');for(const o of r.options){const s=slide(board,o.direction);if(!legal.includes(o.direction)||!Number.isFinite(o.value)||o.gain!==s.score||JSON.stringify(o.afterstate)!==JSON.stringify(s.board))throw new ModelError('invalid_response','The model response did not match the game rules.');}return r;}
export async function modelDecision(board:number[],signal?:AbortSignal):Promise<NtupleDecision>{if(!validNativeBoard(board))throw new ModelError('unsupported_board','This board is outside the native model encoding. No substitute was used.',400);if(!process.env.NTUPLE_SERVICE_URL){if(process.env.VERCEL==='1')throw new ModelError('unavailable','The learned model is not configured.');return nativeDecision(board);}const secret=process.env.NTUPLE_SERVICE_SECRET;if(!secret)throw new ModelError('unavailable','The learned model is not configured.');const url=new URL('/v1/evaluate',process.env.NTUPLE_SERVICE_URL);if(url.protocol!=='https:'&&!(process.env.VERCEL!=='1'&&['127.0.0.1','localhost'].includes(url.hostname)))throw new ModelError('unavailable','The learned model connection is not configured safely.');const start=performance.now();let response:Response;try{response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+secret},body:JSON.stringify({board}),cache:'no-store',signal:signal?AbortSignal.any([signal,AbortSignal.timeout(12000)]):AbortSignal.timeout(12000)});}catch{throw new ModelError('timeout','The model is taking longer to respond. It may be waking. Retry shortly.',504);}if(!response.ok){let code='unavailable';try{const body=await response.json();if(['loading','rate_limited','unavailable','internal_error','invalid_board'].includes(body.code))code=body.code;}catch{}throw new ModelError(code,code==='loading'?'The model is loading. Retry shortly.':code==='rate_limited'?'The model is busy. Retry shortly.':'The model is unavailable or waking. Retry shortly.',response.status===429?429:503);}let r:any;try{r=validateNativeResponse(board,await response.json());}catch(e){if(e instanceof ModelError)throw e;throw new ModelError('invalid_response','The model response could not be validated.');}const ms=performance.now()-start;return {direction:r.direction as Direction,ms,computeMs:r.compute_ms,model:r.model,evidence:{instruction:'Pretrained TD-learning n-tuple policy. Native greedy reward plus afterstate value. The game controller owns rules and spawning.',state:{board:board.slice(),options:r.options.map((o:any)=>({direction:o.direction,board:o.afterstate,reward:o.gain,n_tuple_action_value:o.value}))},checkpoint:r.checkpoint,native_compute_ms:r.compute_ms,remote_request_ms:ms}};}
export function learnedValues(result:NtupleDecision){const e=result.evidence as any;return {direction:result.direction,options:e.state.options.map((o:any)=>({direction:o.direction as Direction,value:o.n_tuple_action_value as number,gain:o.reward as number}))};}
