import {legalMoves,slide,type Direction} from '@/public/engine';
export const DETAIL_LIMIT=128,POINT_LIMIT=2000,MAX_EVIDENCE_BYTES=65536;
export type Measurement={ms:number|null;kind:'measured'|'upper-bound'|'configured'|'unavailable'|'not-applicable'};
export type Stage='queue'|'candidates'|'features'|'expectimax'|'nativeQueue'|'nativeTransport'|'nativeCompute'|'jevHttp'|'parsing'|'audit'|'uiDelay'|'browserTransport'|'total';
export type Timings=Record<Stage,Measurement>;
export type Candidate={label:string;direction:Direction;board:number[];probability:number|null;reward:number;searchValue:number|null;searchRank:number|null;learnedValue:number|null;learnedRank:number|null;searchDepth:number|null;evidence:Record<string,any>};
export type TurnAnalytics={version:'turn-1';move:number;timestamp:string;bot:string;seed:string;before:number[];after:number[];legal:Direction[];direction:Direction;reward:number;score:number;scoreIncrease:number;highest:number;emptyBefore:number;emptyAfter:number;mergesBefore:number;mergesAfter:number;legalNext:Direction[];gameOver:boolean;spawn:{sequence:number;randomDrawOffset:number;cell:number;value:number};schemaVersion:string|null;model:string|null;candidates:Candidate[];candidateOrder:string[];ordering:'shuffled'|'direction-based'|'not-applicable';selectedCandidate:string|null;selectedProbability:number|null;margin:number|null;entropyBits:number|null;probabilityMass:number|null;inputTokens:number|null;outputTokens:number|null;attempts:number;retries:number;errorCategory:string|null;agreesSearch:boolean|null;agreesLearned:boolean|null;overridesSearch:boolean|null;overridesLearned:boolean|null;timing:Timings;timingScope:string;event:boolean;};
export type TurnMeta={timing?:Record<string,number>;serverMs?:number;totalMs?:number|null;browserParseMs?:number;attempts?:number;retries?:number;inputTokens?:number|null;outputTokens?:number|null;errorCategory?:string|null;uiDelay?:number;ultra?:boolean};
export const measurement=(n:unknown,kind:Measurement['kind']='measured'):Measurement=>typeof n==='number'&&Number.isFinite(n)&&n>=0?{ms:n,kind}:{ms:null,kind:'unavailable'};
const absent=()=>measurement(0,'not-applicable');
export function probabilityStats(p:Record<string,number>|null,selected:string|null){if(!p||!Object.keys(p).length||Object.values(p).some(v=>!Number.isFinite(v)||v<0||v>1))return {selectedProbability:null,margin:null,entropyBits:null,probabilityMass:null};const values=Object.values(p).sort((a,b)=>b-a),mass=values.reduce((a,b)=>a+b,0);if(mass<=0)return {selectedProbability:null,margin:null,entropyBits:null,probabilityMass:mass};return {selectedProbability:selected&&typeof p[selected]==='number'?p[selected]:null,margin:values[0]-(values[1]??0),entropyBits:-values.reduce((s,v)=>v?s+(v/mass)*Math.log2(v/mass):s,0),probabilityMass:mass};}
export function safeValue(value:any,depth=0):any{if(depth>14)return '[depth limit]';if(value==null||typeof value==='boolean'||typeof value==='number')return typeof value==='number'&&!Number.isFinite(value)?null:value;if(typeof value==='string')return /Bearer\s+\S+|(?:[A-Za-z]:\\|\/Users\/|\/home\/)|\bsk-[\w-]{12,}/i.test(value)?'[redacted]':value.slice(0,8192);if(Array.isArray(value))return value.slice(0,256).map(v=>safeValue(v,depth+1));if(typeof value!=='object')return null;return Object.fromEntries(Object.entries(value).filter(([k])=>!(/authorization|headers|api.?key|secret|credential|file.?path|raw.?payload|raw.?response/i.test(k))).slice(0,256).map(([k,v])=>[k,safeValue(v,depth+1)]));}
export const schemas=new Map<string,any>();
export function compactEvidence(input:any){if(!input||typeof input!=='object')return undefined;const root:any={};for(const key of ['version','policy','instruction','model_requested','exact_request','candidate_mapping_not_sent','selected_candidate','candidate_probabilities','audit_not_sent','state','options','depth','nodes','native_compute_ms','remote_request_ms','local_request_ms','checkpoint'])if(key in input)root[key]=safeValue(input[key]);if(JSON.stringify(root).length>MAX_EVIDENCE_BYTES)return {version:root.version,evidence_unavailable:'Evidence exceeded the 65,536-character retention bound.'};if(root.exact_request?.questions){const schema={model:root.exact_request.model,questions:root.exact_request.questions},json=JSON.stringify(schema);let hash=2166136261;for(const char of json)hash=Math.imul(hash^char.charCodeAt(0),16777619);let key=(hash>>>0).toString(16);while(schemas.has(key)&&JSON.stringify(schemas.get(key))!==json)key+='x';if(!schemas.has(key)){if(schemas.size>=64)schemas.delete(schemas.keys().next().value!);schemas.set(key,schema);}root.request_schema_id=key;root.exact_request.questions=schemas.get(key).questions;}return root;}
const finite=(n:any):number|null=>typeof n==='number'&&Number.isFinite(n)?n:null;
export function timings(bot:string,ms:number|null,meta:TurnMeta={},evidence:any={}):Timings{const jev=bot.startsWith('blind-')||['raw','strategy','feature','assisted'].includes(bot),native=bot==='ntuple'||['blind-ntuple','blind-dual'].includes(bot),t=meta.timing??{},total=meta.ultra?null:meta.totalMs===undefined?ms:meta.totalMs,unknown=()=>measurement(null);const out:Timings={queue:unknown(),candidates:unknown(),features:unknown(),expectimax:unknown(),nativeQueue:native?unknown():absent(),nativeTransport:native?unknown():absent(),nativeCompute:native?unknown():absent(),jevHttp:jev?unknown():absent(),parsing:unknown(),audit:unknown(),uiDelay:measurement(meta.uiDelay??0,'configured'),browserTransport:unknown(),total:measurement(bot==='human'?null:total)};
 if(jev){out.queue=measurement(t.queue_wait_ms===undefined?undefined:t.queue_wait_ms+(t.worker_queue_ms??0));out.candidates=measurement(t.candidate_generation_formatting_ms);out.features=measurement(t.board_features_ms);out.expectimax=measurement(t.expectimax_evidence_ms);out.jevHttp=measurement(t.jev_http_wait_ms);out.parsing=measurement(meta.browserParseMs);if(meta.serverMs!==undefined&&total!=null)out.browserTransport=measurement(Math.max(0,total-meta.serverMs-(meta.browserParseMs??0)),'upper-bound');}
 if(native){const overall=finite(t.ntuple_total_ms??evidence.local_request_ms??evidence.remote_request_ms),internal=finite(t.ntuple_internal_ms),compute=finite(t.ntuple_compute_ms??evidence.native_compute_ms);out.nativeCompute=measurement(compute);if(overall!==null&&internal!==null){out.nativeQueue=measurement(Math.max(0,overall-internal),'upper-bound');out.nativeTransport=measurement(Math.max(0,internal-(compute??0)),'upper-bound');}else if(overall!==null){out.nativeTransport=measurement(Math.max(0,overall-(compute??0)),'upper-bound');}}
 if(bot==='search')out.expectimax=measurement(ms);if(bot==='human'){for(const k of Object.keys(out) as Stage[])out[k]=k==='total'?unknown():absent();}return out;}
export function makeAnalytics(r:{move:number;policy:string;before:number[];after:number[];direction:Direction;gain:number;spawn:{index:number;value:number};model?:string;ms:number;probabilities:Record<string,number>|null;usage?:{input_tokens:number;output_tokens:number}|null;evidence?:any},seed:string,score:number,meta:TurnMeta={}):TurnAnalytics{
 const e=r.evidence??{},raw=e.exact_request?.state?.candidates??{},mapping=e.candidate_mapping_not_sent??{},prob=e.candidate_probabilities??r.probabilities,selected=e.selected_candidate??(r.probabilities?r.direction:null);const rank=(field:string,v:number|null)=>v===null?null:1+Object.values(raw).filter((c:any)=>finite(field==='search'?c.search?.normalized_expected_value:c.learned?.normalized_afterstate_value)!>v).length;
 const candidates:Candidate[]=Object.entries(raw).filter(([id])=>legalMoves(r.before).includes(mapping[id])).map(([label,c]:[string,any])=>{const search=finite(c.search?.normalized_expected_value),learned=finite(c.learned?.normalized_afterstate_value);return {label,direction:mapping[label],board:c.resulting_board.flat(),reward:c.immediate_merge_reward,probability:finite(prob?.[label]),searchValue:search,searchRank:rank('search',search),learnedValue:learned,learnedRank:rank('learned',learned),searchDepth:finite(c.search?.player_depth),evidence:c};});
 const mergeCount=(b:number[])=>Math.max(0,...legalMoves(b).map(d=>slide(b,d).merges.length)),stats=probabilityStats(prob,selected),audit=e.audit_not_sent??{},agreeSearch=typeof audit.agrees_expectimax==='boolean'?audit.agrees_expectimax:null,agreeLearned=typeof audit.agrees_ntuple==='boolean'?audit.agrees_ntuple:null,legalNext=legalMoves(r.after);const hasUsage=!!r.usage;
 const a:TurnAnalytics={version:'turn-1',move:r.move,timestamp:new Date().toISOString(),bot:r.policy,seed,before:r.before,after:r.after,legal:legalMoves(r.before),direction:r.direction,reward:r.gain,score,scoreIncrease:r.gain,highest:Math.max(...r.after),emptyBefore:r.before.filter(v=>!v).length,emptyAfter:r.after.filter(v=>!v).length,mergesBefore:mergeCount(r.before),mergesAfter:mergeCount(r.after),legalNext,gameOver:legalNext.length===0,spawn:{sequence:r.move+2,randomDrawOffset:2*(r.move+1),cell:r.spawn.index,value:r.spawn.value},schemaVersion:e.version??null,model:r.model??null,candidates,candidateOrder:Object.keys(raw),ordering:candidates.length?'shuffled':r.probabilities?'direction-based':'not-applicable',selectedCandidate:selected,...stats,inputTokens:meta.inputTokens===undefined?(hasUsage?r.usage!.input_tokens:r.probabilities?null:0):meta.inputTokens,outputTokens:meta.outputTokens===undefined?(hasUsage?r.usage!.output_tokens:r.probabilities?null:0):meta.outputTokens,attempts:meta.attempts??0,retries:meta.retries??0,errorCategory:meta.errorCategory??null,agreesSearch:agreeSearch,agreesLearned:agreeLearned,overridesSearch:agreeSearch===null?null:!agreeSearch,overridesLearned:agreeLearned===null?null:!agreeLearned,timing:timings(r.policy,r.ms,meta,e),timingScope:(meta.retries??0)>0?'Stage measurements cover the final attempt; total also includes retries and backoff.':'Stage measurements cover this decision. Deferred audit and configured UI delay are separate.',event:false};a.event=important(a);return a;
}
export function important(a:Pick<TurnAnalytics,'gameOver'|'scoreIncrease'|'margin'|'overridesSearch'|'overridesLearned'|'errorCategory'|'retries'>){return a.gameOver||a.scoreIncrease>=128||(a.margin!==null&&a.margin<.1)||a.overridesSearch===true||a.overridesLearned===true||!!a.errorCategory||a.retries>0;}
export function updateAudit(a:TurnAnalytics,direction:Direction|null,ms:number){a.agreesSearch=direction?direction===a.direction:null;a.overridesSearch=a.agreesSearch===null?null:!a.agreesSearch;a.timing.audit=measurement(ms);a.event=important(a);}
export type NumericTurn=Omit<TurnAnalytics,'before'|'after'|'candidates'|'legal'|'legalNext'|'seed'|'candidateOrder'>;
export function numeric(a:TurnAnalytics):NumericTurn{const {before,after,candidates,legal,legalNext,seed,candidateOrder,...row}=a;return row;}
export function downsample<T extends {move:number;event?:boolean}>(rows:T[],target=400){if(rows.length<=target)return rows;const stride=Math.ceil(rows.length/target);return rows.filter((r,i)=>r.event||i===0||i===rows.length-1||i%stride===0);}
export function agreementCounts(rows:Pick<TurnAnalytics,'agreesSearch'|'agreesLearned'>[]){const out={searchKnown:0,searchAgreed:0,learnedKnown:0,learnedAgreed:0,bothKnown:0,both:0,neither:0,searchOverrides:0,learnedOverrides:0};for(const r of rows){if(r.agreesSearch!==null){out.searchKnown++;r.agreesSearch?out.searchAgreed++:out.searchOverrides++;}if(r.agreesLearned!==null){out.learnedKnown++;r.agreesLearned?out.learnedAgreed++:out.learnedOverrides++;}if(r.agreesSearch!==null&&r.agreesLearned!==null){out.bothKnown++;if(r.agreesSearch&&r.agreesLearned)out.both++;if(!r.agreesSearch&&!r.agreesLearned)out.neither++;}}return out;}
export const stageLabels:Record<Stage,string>={queue:'Request queue',candidates:'Candidate generation / formatting',features:'Board features',expectimax:'Expectimax calculation',nativeQueue:'N-tuple queue',nativeTransport:'N-tuple transport / overhead',nativeCompute:'Native n-tuple compute',jevHttp:'Jev HTTP wait (to headers)',parsing:'Browser response read / parsing',audit:'Deferred audit',uiDelay:'Configured UI delay',browserTransport:'Browser transport / overhead',total:'Total decision time'};
export function timingParts(t:Timings){const sum=(keys:Stage[])=>keys.reduce((n,k)=>n+(t[k].ms??0),0);const parts=[{name:'Local preparation',ms:sum(['queue','candidates','features','expectimax']),color:'#b96325'},{name:'Native model work',ms:sum(['nativeQueue','nativeTransport','nativeCompute']),color:'#087c79'},{name:'Jev HTTP wait',ms:sum(['jevHttp']),color:'#bd365d'},{name:'Parsing',ms:sum(['parsing']),color:'#7746b5'}];const known=parts.reduce((s,p)=>s+p.ms,0);parts.push({name:'Other / unisolated overhead',ms:Math.max(0,(t.total.ms??known)-known),color:'#8b7b92'});return parts;}

export function trimRetained<T,P>(records:T[],points:P[]){if(records.length>DETAIL_LIMIT)records.length=DETAIL_LIMIT;if(points.length>POINT_LIMIT)points.splice(0,points.length-POINT_LIMIT);}
