import Link from 'next/link';
import SiteNav from '@/components/site-nav';
import ResearchChart from '@/components/research-chart';
import ResearchMotion from '@/components/research-motion';
import TimingFigure from '@/components/timing-figure';
import {timings,measurement} from '@/lib/turn-analytics';
import data from '@/public/research-data.json';
import legacy500 from '@/public/legacy-500-moves.json';
import warm from '@/public/diagnostic-warm.json';
const n=(v:number)=>v.toLocaleString('en-US',{maximumFractionDigits:1});
const bots=[
 ['Jev','Board, rules and anonymous legal outcomes','Jev','No','No','Jev'],
 ['Jev + board analysis','Calculated features and two-step structural summaries','Jev','Bounded enumeration','No','Jev'],
 ['Jev + expectimax','Normalized search values and outcome summaries','Jev','Three player plies','No','Jev'],
 ['Jev + n-tuple','Normalized pretrained values and board features','Jev','No','N-tuple','Jev + hosted native if configured'],
 ['Jev + both experts','Separate search summaries and learned values','Jev','Three player plies','N-tuple','Jev + hosted native if configured'],
 ['Expectimax','Board and fixed evaluation function','Search algorithm','Three player plies','No','No'],
 ['N-tuple','Board and pretrained pattern tables','Greedy reward + afterstate value','One-ply evaluation','TD learning','Local: no; hosted: native service']
];
const steps=[['Generate outcomes','Code simulates every legal move, before the random spawn.'],['Shuffle labels','Candidates receive anonymous labels. Direction names are hidden.'],['Add information','Each Jev version receives only its documented features or expert values.'],['Request a choice','One Jev request returns a choice and probabilities over candidates.'],['Validate and map','Code checks the label and maps it back to a legal direction.'],['Move and spawn','Apply the move, score it and use the deterministic seeded spawn stream.']];
export default function ResearchPage(){return <div className="study-shell"><SiteNav active="research"/><main className="concise-research"><ResearchMotion/>
 <section id="tests" className="research-section research-opening"><div><h1>Why I built this</h1><p>I started this because I was curious how Jev would play 2048. Jev makes quick probabilistic choices, and 2048 repeats the same decision hundreds or thousands of times. Every move has a visible result, but the random tile afterward means there is not always one obviously correct answer.</p><p>My first version gave Jev the board and asked it to choose up, down, left, or right. That was not a good use of the model: it had to work out what each move would do before it could compare them. I changed the setup so the game calculates every legal resulting board, hides the direction names, and lets Jev choose between anonymous outcomes.</p><p>Then I wanted to see how its choices changed with more information. One version sees the boards and rules. Another gets empty-cell counts, available merges and tile organization. Others get expectimax search results, learned values from a pretrained n-tuple model, or both.</p><p>Neither specialist tells Jev which move to make. They provide measurements for every outcome, and Jev makes the final choice. The numbers can still make one option look better than another. I want to see how much those different inputs change the same classifier’s decisions.</p></div><aside className="research-scope"><b>What you can try</b><p>Play against Jev, or run several bots side by side. Inspect a move to see what Jev received and what it chose.</p><p>I have not finished a frozen multi-seed test of the current Jev versions. The results below come from earlier comparisons.</p><Link href="/play">Open the game ↗</Link></aside></section>
 <nav className="research-short-nav" aria-label="Research sections"><a href="#bots">Bot comparison</a><a href="#observed">Observations</a><a href="#one-move">One Jev move</a><a href="#timing">Decision time</a><a href="#sources">Limits and sources</a></nav>
 <section id="bots" className="research-section research-bots"><div className="section-side"><h2>How each bot chooses</h2><p>Every Jev version uses Jev 1.13.0 without project-specific training or fine-tuning. Only its inputs change.</p></div><div className="lab-table-scroll"><table><thead><tr><th>Bot</th><th>Information used</th><th>Who chooses</th><th>Search</th><th>Learned values</th><th>API call</th></tr></thead><tbody>{bots.map(([name,...fields])=><tr key={name}><th>{name}</th>{fields.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div><div className="research-data-note"><h3>What Jev sees, and what we record</h3><p>Every Jev version sees the current board and each legal outcome before a new tile appears. Board analysis adds empty space, possible merges, tile ordering, corner stability and mobility. It also measures how possible random spawns affect those features. Expectimax adds estimates from a short search; n-tuple adds learned board values. These are estimates of an outcome’s usefulness, not instructions to pick it.</p><p>Inspect shows the exact information sent for a move, Jev’s choice probabilities and which specialists agreed. Probabilities describe its preference among the options, not its chance of winning. We also record score, largest tile, moves, preparation time, request time, API attempts and tokens. Those measurements describe the game and the work needed to run it; they are not extra hints sent to Jev.</p></div></section>
 <section id="observed" className="research-section research-observations"><div><h2>What we observed</h2><ol className="observation-list"><li><h3>Calculated board information helped</h3><p>Jev did better when code calculated useful board properties and left the choice to it. In a snapshot of three earlier matched seeds at move 500, Feature Jev averaged {n(legacy500.means.feature)} points, slightly above expectimax’s {n(legacy500.means.search)}. Search-assisted Jev averaged {n(legacy500.means.assisted)}. More expert information did not establish a general advantage in the arbitration tests.</p><p className="lab-note">These are legacy versions and a post-hoc 500-move snapshot, not complete-game rankings or results for the current bots. <a href="/legacy-500-moves.json">Scores and source hashes</a>.</p></li><li><h3>N-tuple led this five-seed comparison</h3><p>The pretrained n-tuple bot won {data.matched_wins}/5 matched games. Its mean score was {n(data.matched_means.ntuple.score)}, versus {n(data.matched_means.expectimax.score)} for this expectimax implementation.</p></li><li><h3>Arbitration did not add a demonstrated benefit</h3><p>I also tried asking Jev to settle disagreements between the two specialists. Those tests did not show an advantage over sticking with one specialist. I used only ten states and four short rollouts per move, which was too little to confidently label any of those comparisons.</p></li></ol></div><div className="observed-chart"><ResearchChart data={data.matched.map(r=>({label:r.label,expectimax:r.expectimax.score,ntuple:r.ntuple.score}))} series={[{key:'expectimax',name:'Expectimax',color:'#7746b5'},{key:'ntuple',name:'N-tuple',color:'#087c79'}]} label="Final scores · five matched seeds per bot · descriptive results"/><p>Both bots received the same tile-value and shuffled cell-priority streams. Actual spawn cells can differ after their moves change board occupancy.</p></div></section>
 <section id="one-move" className="research-section research-one-move"><h2>What happens during one Jev move</h2><div className="six-step-loop">{steps.map(([title,body],i)=><article key={title}><span>{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div><p className="lab-note">Jev sees no direction names, specialist recommendation or actual future spawn. Numeric expert values can still reveal relative preferences. Specialist agreement audits run asynchronously after the move.</p></section>
 <section id="timing" className="research-section research-decision-time"><div className="section-side"><h2>Decision time</h2><p>Each Jev version makes one API request per move, but the complete decision also includes preparing its inputs.</p><p>In one warm diagnostic, plain Jev took <b>{Math.round(warm.results[0].total_ms)} ms</b>, board analysis <b>{Math.round(warm.results[1].total_ms)} ms</b>, and both experts <b>{Math.round(warm.results[2].total_ms)} ms</b>. These are single samples, not benchmark averages or isolated inference times.</p></div><div className="diagnostic-compositions">{warm.results.map((r,i)=>{const t=timings(r.policy,r.total_ms,{timing:{...Object.fromEntries(Object.entries(r).filter(([,v])=>typeof v==='number')) as Record<string,number>,jev_http_wait_ms:r.network_headers_ms},totalMs:r.total_ms,browserParseMs:r.response_body_parse_ms});t.parsing=measurement(r.response_body_parse_ms);return <article key={r.policy} style={{'--timing-ratio':(r.total_ms/Math.max(...warm.results.map(v=>v.total_ms))*100)+'%'} as React.CSSProperties}><h3>{['Plain Jev','Jev with board analysis','Jev with both experts'][i]} <span>{Math.round(r.total_ms)} ms</span></h3><TimingFigure timing={t} compact/></article>})}</div>
 <div className="lab-table-scroll"><table><caption>{warm.date.slice(0,10)} · one warm sample per version · milliseconds · no retries</caption><thead><tr><th>Input version</th><th>Features + formatting</th><th>Expectimax</th><th>Native queue¹</th><th>Native transport¹</th><th>Jev HTTP wait</th><th>Body read²</th><th>Total</th></tr></thead><tbody>{warm.results.map((r,i)=><tr key={r.policy}><th>{['Board and rules','Board analysis','Both experts'][i]}</th><td>{(r.board_features_ms+r.candidate_generation_formatting_ms).toFixed(1)}</td><td>{r.expectimax_evidence_ms.toFixed(1)}</td><td>{r.ntuple_queue_upper_bound_ms.toFixed(1)}</td><td>{Math.max(0,r.ntuple_internal_ms-r.ntuple_compute_ms).toFixed(1)}</td><td>{r.network_headers_ms.toFixed(1)}</td><td>{r.response_body_parse_ms.toFixed(2)}</td><td>{Math.round(r.total_ms)}</td></tr>)}</tbody></table></div>
 <div className="timing-notes"><p>Board analysis spent about 801 ms on two-step structural features. Expectimax evidence took about 115 ms in the both-experts sample. Native n-tuple computation took 0.009 ms, while its queue and transport took about 171 ms. Native compute is not hosted response time.</p><p>More supplied information did not always produce a slower decision. The largest delay came from calculating two-step board features, not from the number of Jev questions.</p><p className="lab-note">¹ Native queue and transport are upper-bound residuals. ² Body read was measured; JSON parsing was not isolated. The bar leaves other time in overhead. Workers were warmed first. Browser transport, deferred audit and UI delay are excluded from these saved totals. Normal mode’s configured delay occurs between decisions. Live Inspect labels each measurement separately. Lower latency does not imply better gameplay.</p></div></section>
 <section id="sources" className="research-section research-limits"><span id="attribution"/><div><h2>Limitations and sources</h2><p>These are small tests, and random spawns change how games turn out. A high Jev probability does not mean a good move or a likely win. I still need to test the current versions across a fixed set of seeds. When n-tuple runs on a hosted server, its displayed time also includes the network request and sometimes waking the server. The verified native encoding supports tiles up to 32,768. If any legal outcome would exceed that, n-tuple-dependent bots stop with an explicit error; they never switch to another bot.</p></div><ul className="source-links"><li><a href="https://typesafe.ai">TypeSafe Jev</a> · classifier API</li><li><a href="https://github.com/moporgic/TDL2048">TDL2048+ by Hung Guei</a> · <a href="/licenses/TDL2048-MIT.txt">MIT license</a> · <a href="/checkpoint-provenance.json">checkpoint provenance</a></li><li><a href="https://github.com/nneonneo/2048-ai">2048-ai by Robert Xiao and contributors</a> · adapted expectimax · <a href="/licenses/nneonneo-MIT.txt">MIT license</a></li></ul><details className="development-notes"><summary>Development notes and saved results</summary><p>Legacy direction-based Jev, strategy instructions, the fixed heuristic, uncertainty gates, tail-risk tests and both arbitration studies remain in the saved artifacts. They are distinct experiments, not results for the current bots. <a href="/research-data.json" download>Download the recorded results and original artifact hashes</a>.</p><p>The native checkpoint was validated at commit a99f620aec0d30a75943a4c9646743f1f53b0197. This project adds Jev requests, comparison orchestration and UI; upstream repositories do not contain that integration.</p></details></section>
 </main><footer className="study-footer"><Link href="/play">Back to Play</Link><a href="https://armanhassan.com">Check out my other work</a></footer></div>;}
